// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public interface BoatDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.BoatDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  com.google.protobuf.Int32Value getId();
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.StringValue make = 3;</code>
   */
  boolean hasMake();
  /**
   * <code>.google.protobuf.StringValue make = 3;</code>
   */
  com.google.protobuf.StringValue getMake();
  /**
   * <code>.google.protobuf.StringValue make = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getMakeOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue length = 4;</code>
   */
  boolean hasLength();
  /**
   * <code>.google.protobuf.DoubleValue length = 4;</code>
   */
  com.google.protobuf.DoubleValue getLength();
  /**
   * <code>.google.protobuf.DoubleValue length = 4;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getLengthOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value rating = 5;</code>
   */
  boolean hasRating();
  /**
   * <code>.google.protobuf.Int32Value rating = 5;</code>
   */
  com.google.protobuf.Int32Value getRating();
  /**
   * <code>.google.protobuf.Int32Value rating = 5;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 6;</code>
   */
  boolean hasSkipper();
  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 6;</code>
   */
  org.seasailing.protobuf.PersonDTO getSkipper();
  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 6;</code>
   */
  org.seasailing.protobuf.PersonDTOOrBuilder getSkipperOrBuilder();

  /**
   * <code>.google.protobuf.BoolValue active = 7;</code>
   */
  boolean hasActive();
  /**
   * <code>.google.protobuf.BoolValue active = 7;</code>
   */
  com.google.protobuf.BoolValue getActive();
  /**
   * <code>.google.protobuf.BoolValue active = 7;</code>
   */
  com.google.protobuf.BoolValueOrBuilder getActiveOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 8;</code>
   */
  boolean hasClub();
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 8;</code>
   */
  org.seasailing.protobuf.ClubDTO getClub();
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 8;</code>
   */
  org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder();
}
