// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.BoatDTO}
 */
public  final class BoatDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.BoatDTO)
    BoatDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BoatDTO.newBuilder() to construct.
  private BoatDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BoatDTO() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BoatDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(org.seasailing.protobuf.BoatDTO.BoatNameDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (make_ != null) {
              subBuilder = make_.toBuilder();
            }
            make_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(make_);
              make_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.DoubleValue.Builder subBuilder = null;
            if (length_ != null) {
              subBuilder = length_.toBuilder();
            }
            length_ = input.readMessage(com.google.protobuf.DoubleValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(length_);
              length_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (rating_ != null) {
              subBuilder = rating_.toBuilder();
            }
            rating_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rating_);
              rating_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            org.seasailing.protobuf.PersonDTO.Builder subBuilder = null;
            if (skipper_ != null) {
              subBuilder = skipper_.toBuilder();
            }
            skipper_ = input.readMessage(org.seasailing.protobuf.PersonDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(skipper_);
              skipper_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.BoolValue.Builder subBuilder = null;
            if (active_ != null) {
              subBuilder = active_.toBuilder();
            }
            active_ = input.readMessage(com.google.protobuf.BoolValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(active_);
              active_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            org.seasailing.protobuf.ClubDTO.Builder subBuilder = null;
            if (club_ != null) {
              subBuilder = club_.toBuilder();
            }
            club_ = input.readMessage(org.seasailing.protobuf.ClubDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(club_);
              club_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.BoatDTO.class, org.seasailing.protobuf.BoatDTO.Builder.class);
  }

  public interface BoatNameDTOOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.BoatDTO.BoatNameDTO)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    com.google.protobuf.Int32Value getId();
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder();

    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    com.google.protobuf.StringValue getName();
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    com.google.protobuf.StringValueOrBuilder getNameOrBuilder();
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.BoatDTO.BoatNameDTO}
   */
  public  static final class BoatNameDTO extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.BoatDTO.BoatNameDTO)
      BoatNameDTOOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BoatNameDTO.newBuilder() to construct.
    private BoatNameDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BoatNameDTO() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BoatNameDTO(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.Int32Value.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.StringValue.Builder subBuilder = null;
              if (name_ != null) {
                subBuilder = name_.toBuilder();
              }
              name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(name_);
                name_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.BoatDTO.BoatNameDTO.class, org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.Int32Value id_;
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value getId() {
      return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
      return getId();
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.StringValue name_;
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public boolean hasName() {
      return name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue getName() {
      return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      return getName();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (name_ != null) {
        output.writeMessage(2, getName());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (name_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getName());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.seasailing.protobuf.BoatDTO.BoatNameDTO)) {
        return super.equals(obj);
      }
      org.seasailing.protobuf.BoatDTO.BoatNameDTO other = (org.seasailing.protobuf.BoatDTO.BoatNameDTO) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.seasailing.protobuf.BoatDTO.BoatNameDTO prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.seasailing.protobuf.BoatDTO.BoatNameDTO}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.BoatDTO.BoatNameDTO)
        org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.seasailing.protobuf.BoatDTO.BoatNameDTO.class, org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder.class);
      }

      // Construct using org.seasailing.protobuf.BoatDTO.BoatNameDTO.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        if (nameBuilder_ == null) {
          name_ = null;
        } else {
          name_ = null;
          nameBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor;
      }

      public org.seasailing.protobuf.BoatDTO.BoatNameDTO getDefaultInstanceForType() {
        return org.seasailing.protobuf.BoatDTO.BoatNameDTO.getDefaultInstance();
      }

      public org.seasailing.protobuf.BoatDTO.BoatNameDTO build() {
        org.seasailing.protobuf.BoatDTO.BoatNameDTO result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.seasailing.protobuf.BoatDTO.BoatNameDTO buildPartial() {
        org.seasailing.protobuf.BoatDTO.BoatNameDTO result = new org.seasailing.protobuf.BoatDTO.BoatNameDTO(this);
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (nameBuilder_ == null) {
          result.name_ = name_;
        } else {
          result.name_ = nameBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.seasailing.protobuf.BoatDTO.BoatNameDTO) {
          return mergeFrom((org.seasailing.protobuf.BoatDTO.BoatNameDTO)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.seasailing.protobuf.BoatDTO.BoatNameDTO other) {
        if (other == org.seasailing.protobuf.BoatDTO.BoatNameDTO.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasName()) {
          mergeName(other.getName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.seasailing.protobuf.BoatDTO.BoatNameDTO parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.seasailing.protobuf.BoatDTO.BoatNameDTO) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Int32Value id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> idBuilder_;
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public com.google.protobuf.Int32Value getId() {
        if (idBuilder_ == null) {
          return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public Builder setId(com.google.protobuf.Int32Value value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public Builder setId(
          com.google.protobuf.Int32Value.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public Builder mergeId(com.google.protobuf.Int32Value value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              com.google.protobuf.Int32Value.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public com.google.protobuf.Int32Value.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              com.google.protobuf.Int32Value.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.google.protobuf.Int32Value id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private com.google.protobuf.StringValue name_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public boolean hasName() {
        return nameBuilder_ != null || name_ != null;
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public com.google.protobuf.StringValue getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public Builder setName(com.google.protobuf.StringValue value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
          onChanged();
        } else {
          nameBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public Builder setName(
          com.google.protobuf.StringValue.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
          onChanged();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public Builder mergeName(com.google.protobuf.StringValue value) {
        if (nameBuilder_ == null) {
          if (name_ != null) {
            name_ =
              com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
          } else {
            name_ = value;
          }
          onChanged();
        } else {
          nameBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public Builder clearName() {
        if (nameBuilder_ == null) {
          name_ = null;
          onChanged();
        } else {
          name_ = null;
          nameBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public com.google.protobuf.StringValue.Builder getNameBuilder() {
        
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              com.google.protobuf.StringValue.getDefaultInstance() : name_;
        }
      }
      /**
       * <code>.google.protobuf.StringValue name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.BoatDTO.BoatNameDTO)
    }

    // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.BoatDTO.BoatNameDTO)
    private static final org.seasailing.protobuf.BoatDTO.BoatNameDTO DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.seasailing.protobuf.BoatDTO.BoatNameDTO();
    }

    public static org.seasailing.protobuf.BoatDTO.BoatNameDTO getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BoatNameDTO>
        PARSER = new com.google.protobuf.AbstractParser<BoatNameDTO>() {
      public BoatNameDTO parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BoatNameDTO(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BoatNameDTO> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BoatNameDTO> getParserForType() {
      return PARSER;
    }

    public org.seasailing.protobuf.BoatDTO.BoatNameDTO getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int NAME_FIELD_NUMBER = 1;
  private org.seasailing.protobuf.BoatDTO.BoatNameDTO name_;
  /**
   * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
   */
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
   */
  public org.seasailing.protobuf.BoatDTO.BoatNameDTO getName() {
    return name_ == null ? org.seasailing.protobuf.BoatDTO.BoatNameDTO.getDefaultInstance() : name_;
  }
  /**
   * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
   */
  public org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int MAKE_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue make_;
  /**
   * <code>.google.protobuf.StringValue make = 2;</code>
   */
  public boolean hasMake() {
    return make_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue make = 2;</code>
   */
  public com.google.protobuf.StringValue getMake() {
    return make_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : make_;
  }
  /**
   * <code>.google.protobuf.StringValue make = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getMakeOrBuilder() {
    return getMake();
  }

  public static final int LENGTH_FIELD_NUMBER = 3;
  private com.google.protobuf.DoubleValue length_;
  /**
   * <code>.google.protobuf.DoubleValue length = 3;</code>
   */
  public boolean hasLength() {
    return length_ != null;
  }
  /**
   * <code>.google.protobuf.DoubleValue length = 3;</code>
   */
  public com.google.protobuf.DoubleValue getLength() {
    return length_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : length_;
  }
  /**
   * <code>.google.protobuf.DoubleValue length = 3;</code>
   */
  public com.google.protobuf.DoubleValueOrBuilder getLengthOrBuilder() {
    return getLength();
  }

  public static final int RATING_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value rating_;
  /**
   * <code>.google.protobuf.Int32Value rating = 4;</code>
   */
  public boolean hasRating() {
    return rating_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value rating = 4;</code>
   */
  public com.google.protobuf.Int32Value getRating() {
    return rating_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
  }
  /**
   * <code>.google.protobuf.Int32Value rating = 4;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder() {
    return getRating();
  }

  public static final int SKIPPER_FIELD_NUMBER = 5;
  private org.seasailing.protobuf.PersonDTO skipper_;
  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
   */
  public boolean hasSkipper() {
    return skipper_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
   */
  public org.seasailing.protobuf.PersonDTO getSkipper() {
    return skipper_ == null ? org.seasailing.protobuf.PersonDTO.getDefaultInstance() : skipper_;
  }
  /**
   * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
   */
  public org.seasailing.protobuf.PersonDTOOrBuilder getSkipperOrBuilder() {
    return getSkipper();
  }

  public static final int ACTIVE_FIELD_NUMBER = 6;
  private com.google.protobuf.BoolValue active_;
  /**
   * <code>.google.protobuf.BoolValue active = 6;</code>
   */
  public boolean hasActive() {
    return active_ != null;
  }
  /**
   * <code>.google.protobuf.BoolValue active = 6;</code>
   */
  public com.google.protobuf.BoolValue getActive() {
    return active_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : active_;
  }
  /**
   * <code>.google.protobuf.BoolValue active = 6;</code>
   */
  public com.google.protobuf.BoolValueOrBuilder getActiveOrBuilder() {
    return getActive();
  }

  public static final int CLUB_FIELD_NUMBER = 7;
  private org.seasailing.protobuf.ClubDTO club_;
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
   */
  public boolean hasClub() {
    return club_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
   */
  public org.seasailing.protobuf.ClubDTO getClub() {
    return club_ == null ? org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
  }
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
   */
  public org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder() {
    return getClub();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (name_ != null) {
      output.writeMessage(1, getName());
    }
    if (make_ != null) {
      output.writeMessage(2, getMake());
    }
    if (length_ != null) {
      output.writeMessage(3, getLength());
    }
    if (rating_ != null) {
      output.writeMessage(4, getRating());
    }
    if (skipper_ != null) {
      output.writeMessage(5, getSkipper());
    }
    if (active_ != null) {
      output.writeMessage(6, getActive());
    }
    if (club_ != null) {
      output.writeMessage(7, getClub());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getName());
    }
    if (make_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getMake());
    }
    if (length_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLength());
    }
    if (rating_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRating());
    }
    if (skipper_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSkipper());
    }
    if (active_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getActive());
    }
    if (club_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getClub());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.BoatDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.BoatDTO other = (org.seasailing.protobuf.BoatDTO) obj;

    boolean result = true;
    result = result && (hasName() == other.hasName());
    if (hasName()) {
      result = result && getName()
          .equals(other.getName());
    }
    result = result && (hasMake() == other.hasMake());
    if (hasMake()) {
      result = result && getMake()
          .equals(other.getMake());
    }
    result = result && (hasLength() == other.hasLength());
    if (hasLength()) {
      result = result && getLength()
          .equals(other.getLength());
    }
    result = result && (hasRating() == other.hasRating());
    if (hasRating()) {
      result = result && getRating()
          .equals(other.getRating());
    }
    result = result && (hasSkipper() == other.hasSkipper());
    if (hasSkipper()) {
      result = result && getSkipper()
          .equals(other.getSkipper());
    }
    result = result && (hasActive() == other.hasActive());
    if (hasActive()) {
      result = result && getActive()
          .equals(other.getActive());
    }
    result = result && (hasClub() == other.hasClub());
    if (hasClub()) {
      result = result && getClub()
          .equals(other.getClub());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasMake()) {
      hash = (37 * hash) + MAKE_FIELD_NUMBER;
      hash = (53 * hash) + getMake().hashCode();
    }
    if (hasLength()) {
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength().hashCode();
    }
    if (hasRating()) {
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating().hashCode();
    }
    if (hasSkipper()) {
      hash = (37 * hash) + SKIPPER_FIELD_NUMBER;
      hash = (53 * hash) + getSkipper().hashCode();
    }
    if (hasActive()) {
      hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + getActive().hashCode();
    }
    if (hasClub()) {
      hash = (37 * hash) + CLUB_FIELD_NUMBER;
      hash = (53 * hash) + getClub().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.BoatDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.BoatDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.BoatDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.BoatDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.BoatDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.BoatDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.BoatDTO)
      org.seasailing.protobuf.BoatDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.BoatDTO.class, org.seasailing.protobuf.BoatDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.BoatDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (makeBuilder_ == null) {
        make_ = null;
      } else {
        make_ = null;
        makeBuilder_ = null;
      }
      if (lengthBuilder_ == null) {
        length_ = null;
      } else {
        length_ = null;
        lengthBuilder_ = null;
      }
      if (ratingBuilder_ == null) {
        rating_ = null;
      } else {
        rating_ = null;
        ratingBuilder_ = null;
      }
      if (skipperBuilder_ == null) {
        skipper_ = null;
      } else {
        skipper_ = null;
        skipperBuilder_ = null;
      }
      if (activeBuilder_ == null) {
        active_ = null;
      } else {
        active_ = null;
        activeBuilder_ = null;
      }
      if (clubBuilder_ == null) {
        club_ = null;
      } else {
        club_ = null;
        clubBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_BoatDTO_descriptor;
    }

    public org.seasailing.protobuf.BoatDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.BoatDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.BoatDTO build() {
      org.seasailing.protobuf.BoatDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.BoatDTO buildPartial() {
      org.seasailing.protobuf.BoatDTO result = new org.seasailing.protobuf.BoatDTO(this);
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (makeBuilder_ == null) {
        result.make_ = make_;
      } else {
        result.make_ = makeBuilder_.build();
      }
      if (lengthBuilder_ == null) {
        result.length_ = length_;
      } else {
        result.length_ = lengthBuilder_.build();
      }
      if (ratingBuilder_ == null) {
        result.rating_ = rating_;
      } else {
        result.rating_ = ratingBuilder_.build();
      }
      if (skipperBuilder_ == null) {
        result.skipper_ = skipper_;
      } else {
        result.skipper_ = skipperBuilder_.build();
      }
      if (activeBuilder_ == null) {
        result.active_ = active_;
      } else {
        result.active_ = activeBuilder_.build();
      }
      if (clubBuilder_ == null) {
        result.club_ = club_;
      } else {
        result.club_ = clubBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.BoatDTO) {
        return mergeFrom((org.seasailing.protobuf.BoatDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.BoatDTO other) {
      if (other == org.seasailing.protobuf.BoatDTO.getDefaultInstance()) return this;
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasMake()) {
        mergeMake(other.getMake());
      }
      if (other.hasLength()) {
        mergeLength(other.getLength());
      }
      if (other.hasRating()) {
        mergeRating(other.getRating());
      }
      if (other.hasSkipper()) {
        mergeSkipper(other.getSkipper());
      }
      if (other.hasActive()) {
        mergeActive(other.getActive());
      }
      if (other.hasClub()) {
        mergeClub(other.getClub());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.BoatDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.BoatDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.seasailing.protobuf.BoatDTO.BoatNameDTO name_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.BoatDTO.BoatNameDTO, org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder, org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder> nameBuilder_;
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTO.BoatNameDTO getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? org.seasailing.protobuf.BoatDTO.BoatNameDTO.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public Builder setName(org.seasailing.protobuf.BoatDTO.BoatNameDTO value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public Builder setName(
        org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public Builder mergeName(org.seasailing.protobuf.BoatDTO.BoatNameDTO value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            org.seasailing.protobuf.BoatDTO.BoatNameDTO.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            org.seasailing.protobuf.BoatDTO.BoatNameDTO.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO.BoatNameDTO name = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.BoatDTO.BoatNameDTO, org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder, org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.BoatDTO.BoatNameDTO, org.seasailing.protobuf.BoatDTO.BoatNameDTO.Builder, org.seasailing.protobuf.BoatDTO.BoatNameDTOOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.StringValue make_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> makeBuilder_;
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public boolean hasMake() {
      return makeBuilder_ != null || make_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public com.google.protobuf.StringValue getMake() {
      if (makeBuilder_ == null) {
        return make_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : make_;
      } else {
        return makeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public Builder setMake(com.google.protobuf.StringValue value) {
      if (makeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        make_ = value;
        onChanged();
      } else {
        makeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public Builder setMake(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (makeBuilder_ == null) {
        make_ = builderForValue.build();
        onChanged();
      } else {
        makeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public Builder mergeMake(com.google.protobuf.StringValue value) {
      if (makeBuilder_ == null) {
        if (make_ != null) {
          make_ =
            com.google.protobuf.StringValue.newBuilder(make_).mergeFrom(value).buildPartial();
        } else {
          make_ = value;
        }
        onChanged();
      } else {
        makeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public Builder clearMake() {
      if (makeBuilder_ == null) {
        make_ = null;
        onChanged();
      } else {
        make_ = null;
        makeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getMakeBuilder() {
      
      onChanged();
      return getMakeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getMakeOrBuilder() {
      if (makeBuilder_ != null) {
        return makeBuilder_.getMessageOrBuilder();
      } else {
        return make_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : make_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue make = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getMakeFieldBuilder() {
      if (makeBuilder_ == null) {
        makeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getMake(),
                getParentForChildren(),
                isClean());
        make_ = null;
      }
      return makeBuilder_;
    }

    private com.google.protobuf.DoubleValue length_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> lengthBuilder_;
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public boolean hasLength() {
      return lengthBuilder_ != null || length_ != null;
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public com.google.protobuf.DoubleValue getLength() {
      if (lengthBuilder_ == null) {
        return length_ == null ? com.google.protobuf.DoubleValue.getDefaultInstance() : length_;
      } else {
        return lengthBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public Builder setLength(com.google.protobuf.DoubleValue value) {
      if (lengthBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        length_ = value;
        onChanged();
      } else {
        lengthBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public Builder setLength(
        com.google.protobuf.DoubleValue.Builder builderForValue) {
      if (lengthBuilder_ == null) {
        length_ = builderForValue.build();
        onChanged();
      } else {
        lengthBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public Builder mergeLength(com.google.protobuf.DoubleValue value) {
      if (lengthBuilder_ == null) {
        if (length_ != null) {
          length_ =
            com.google.protobuf.DoubleValue.newBuilder(length_).mergeFrom(value).buildPartial();
        } else {
          length_ = value;
        }
        onChanged();
      } else {
        lengthBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public Builder clearLength() {
      if (lengthBuilder_ == null) {
        length_ = null;
        onChanged();
      } else {
        length_ = null;
        lengthBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public com.google.protobuf.DoubleValue.Builder getLengthBuilder() {
      
      onChanged();
      return getLengthFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    public com.google.protobuf.DoubleValueOrBuilder getLengthOrBuilder() {
      if (lengthBuilder_ != null) {
        return lengthBuilder_.getMessageOrBuilder();
      } else {
        return length_ == null ?
            com.google.protobuf.DoubleValue.getDefaultInstance() : length_;
      }
    }
    /**
     * <code>.google.protobuf.DoubleValue length = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder> 
        getLengthFieldBuilder() {
      if (lengthBuilder_ == null) {
        lengthBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.DoubleValue, com.google.protobuf.DoubleValue.Builder, com.google.protobuf.DoubleValueOrBuilder>(
                getLength(),
                getParentForChildren(),
                isClean());
        length_ = null;
      }
      return lengthBuilder_;
    }

    private com.google.protobuf.Int32Value rating_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> ratingBuilder_;
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public boolean hasRating() {
      return ratingBuilder_ != null || rating_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public com.google.protobuf.Int32Value getRating() {
      if (ratingBuilder_ == null) {
        return rating_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
      } else {
        return ratingBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public Builder setRating(com.google.protobuf.Int32Value value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rating_ = value;
        onChanged();
      } else {
        ratingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public Builder setRating(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        rating_ = builderForValue.build();
        onChanged();
      } else {
        ratingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public Builder mergeRating(com.google.protobuf.Int32Value value) {
      if (ratingBuilder_ == null) {
        if (rating_ != null) {
          rating_ =
            com.google.protobuf.Int32Value.newBuilder(rating_).mergeFrom(value).buildPartial();
        } else {
          rating_ = value;
        }
        onChanged();
      } else {
        ratingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public Builder clearRating() {
      if (ratingBuilder_ == null) {
        rating_ = null;
        onChanged();
      } else {
        rating_ = null;
        ratingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public com.google.protobuf.Int32Value.Builder getRatingBuilder() {
      
      onChanged();
      return getRatingFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder() {
      if (ratingBuilder_ != null) {
        return ratingBuilder_.getMessageOrBuilder();
      } else {
        return rating_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getRatingFieldBuilder() {
      if (ratingBuilder_ == null) {
        ratingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getRating(),
                getParentForChildren(),
                isClean());
        rating_ = null;
      }
      return ratingBuilder_;
    }

    private org.seasailing.protobuf.PersonDTO skipper_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder> skipperBuilder_;
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public boolean hasSkipper() {
      return skipperBuilder_ != null || skipper_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public org.seasailing.protobuf.PersonDTO getSkipper() {
      if (skipperBuilder_ == null) {
        return skipper_ == null ? org.seasailing.protobuf.PersonDTO.getDefaultInstance() : skipper_;
      } else {
        return skipperBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public Builder setSkipper(org.seasailing.protobuf.PersonDTO value) {
      if (skipperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        skipper_ = value;
        onChanged();
      } else {
        skipperBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public Builder setSkipper(
        org.seasailing.protobuf.PersonDTO.Builder builderForValue) {
      if (skipperBuilder_ == null) {
        skipper_ = builderForValue.build();
        onChanged();
      } else {
        skipperBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public Builder mergeSkipper(org.seasailing.protobuf.PersonDTO value) {
      if (skipperBuilder_ == null) {
        if (skipper_ != null) {
          skipper_ =
            org.seasailing.protobuf.PersonDTO.newBuilder(skipper_).mergeFrom(value).buildPartial();
        } else {
          skipper_ = value;
        }
        onChanged();
      } else {
        skipperBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public Builder clearSkipper() {
      if (skipperBuilder_ == null) {
        skipper_ = null;
        onChanged();
      } else {
        skipper_ = null;
        skipperBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public org.seasailing.protobuf.PersonDTO.Builder getSkipperBuilder() {
      
      onChanged();
      return getSkipperFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    public org.seasailing.protobuf.PersonDTOOrBuilder getSkipperOrBuilder() {
      if (skipperBuilder_ != null) {
        return skipperBuilder_.getMessageOrBuilder();
      } else {
        return skipper_ == null ?
            org.seasailing.protobuf.PersonDTO.getDefaultInstance() : skipper_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO skipper = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder> 
        getSkipperFieldBuilder() {
      if (skipperBuilder_ == null) {
        skipperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder>(
                getSkipper(),
                getParentForChildren(),
                isClean());
        skipper_ = null;
      }
      return skipperBuilder_;
    }

    private com.google.protobuf.BoolValue active_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> activeBuilder_;
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public boolean hasActive() {
      return activeBuilder_ != null || active_ != null;
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public com.google.protobuf.BoolValue getActive() {
      if (activeBuilder_ == null) {
        return active_ == null ? com.google.protobuf.BoolValue.getDefaultInstance() : active_;
      } else {
        return activeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public Builder setActive(com.google.protobuf.BoolValue value) {
      if (activeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        active_ = value;
        onChanged();
      } else {
        activeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public Builder setActive(
        com.google.protobuf.BoolValue.Builder builderForValue) {
      if (activeBuilder_ == null) {
        active_ = builderForValue.build();
        onChanged();
      } else {
        activeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public Builder mergeActive(com.google.protobuf.BoolValue value) {
      if (activeBuilder_ == null) {
        if (active_ != null) {
          active_ =
            com.google.protobuf.BoolValue.newBuilder(active_).mergeFrom(value).buildPartial();
        } else {
          active_ = value;
        }
        onChanged();
      } else {
        activeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public Builder clearActive() {
      if (activeBuilder_ == null) {
        active_ = null;
        onChanged();
      } else {
        active_ = null;
        activeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public com.google.protobuf.BoolValue.Builder getActiveBuilder() {
      
      onChanged();
      return getActiveFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    public com.google.protobuf.BoolValueOrBuilder getActiveOrBuilder() {
      if (activeBuilder_ != null) {
        return activeBuilder_.getMessageOrBuilder();
      } else {
        return active_ == null ?
            com.google.protobuf.BoolValue.getDefaultInstance() : active_;
      }
    }
    /**
     * <code>.google.protobuf.BoolValue active = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder> 
        getActiveFieldBuilder() {
      if (activeBuilder_ == null) {
        activeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.BoolValue, com.google.protobuf.BoolValue.Builder, com.google.protobuf.BoolValueOrBuilder>(
                getActive(),
                getParentForChildren(),
                isClean());
        active_ = null;
      }
      return activeBuilder_;
    }

    private org.seasailing.protobuf.ClubDTO club_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder> clubBuilder_;
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public boolean hasClub() {
      return clubBuilder_ != null || club_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public org.seasailing.protobuf.ClubDTO getClub() {
      if (clubBuilder_ == null) {
        return club_ == null ? org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
      } else {
        return clubBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public Builder setClub(org.seasailing.protobuf.ClubDTO value) {
      if (clubBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        club_ = value;
        onChanged();
      } else {
        clubBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public Builder setClub(
        org.seasailing.protobuf.ClubDTO.Builder builderForValue) {
      if (clubBuilder_ == null) {
        club_ = builderForValue.build();
        onChanged();
      } else {
        clubBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public Builder mergeClub(org.seasailing.protobuf.ClubDTO value) {
      if (clubBuilder_ == null) {
        if (club_ != null) {
          club_ =
            org.seasailing.protobuf.ClubDTO.newBuilder(club_).mergeFrom(value).buildPartial();
        } else {
          club_ = value;
        }
        onChanged();
      } else {
        clubBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public Builder clearClub() {
      if (clubBuilder_ == null) {
        club_ = null;
        onChanged();
      } else {
        club_ = null;
        clubBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public org.seasailing.protobuf.ClubDTO.Builder getClubBuilder() {
      
      onChanged();
      return getClubFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    public org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder() {
      if (clubBuilder_ != null) {
        return clubBuilder_.getMessageOrBuilder();
      } else {
        return club_ == null ?
            org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder> 
        getClubFieldBuilder() {
      if (clubBuilder_ == null) {
        clubBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder>(
                getClub(),
                getParentForChildren(),
                isClean());
        club_ = null;
      }
      return clubBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.BoatDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.BoatDTO)
  private static final org.seasailing.protobuf.BoatDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.BoatDTO();
  }

  public static org.seasailing.protobuf.BoatDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BoatDTO>
      PARSER = new com.google.protobuf.AbstractParser<BoatDTO>() {
    public BoatDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BoatDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BoatDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BoatDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.BoatDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

