// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.ClubDTO}
 */
public  final class ClubDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.ClubDTO)
    ClubDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClubDTO.newBuilder() to construct.
  private ClubDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClubDTO() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClubDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (email_ != null) {
              subBuilder = email_.toBuilder();
            }
            email_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(email_);
              email_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.seasailing.protobuf.PersonDTO.Builder subBuilder = null;
            if (handicapper_ != null) {
              subBuilder = handicapper_.toBuilder();
            }
            handicapper_ = input.readMessage(org.seasailing.protobuf.PersonDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(handicapper_);
              handicapper_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            org.seasailing.protobuf.HandicapDTO.Builder subBuilder = null;
            if (defaultHandicap_ != null) {
              subBuilder = defaultHandicap_.toBuilder();
            }
            defaultHandicap_ = input.readMessage(org.seasailing.protobuf.HandicapDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(defaultHandicap_);
              defaultHandicap_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ClubDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ClubDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.ClubDTO.class, org.seasailing.protobuf.ClubDTO.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value id_;
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32Value getId() {
    return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue name_;
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public com.google.protobuf.StringValue getName() {
    return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int EMAIL_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue email_;
  /**
   * <code>.google.protobuf.StringValue email = 3;</code>
   */
  public boolean hasEmail() {
    return email_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue email = 3;</code>
   */
  public com.google.protobuf.StringValue getEmail() {
    return email_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : email_;
  }
  /**
   * <code>.google.protobuf.StringValue email = 3;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getEmailOrBuilder() {
    return getEmail();
  }

  public static final int HANDICAPPER_FIELD_NUMBER = 4;
  private org.seasailing.protobuf.PersonDTO handicapper_;
  /**
   * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
   */
  public boolean hasHandicapper() {
    return handicapper_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
   */
  public org.seasailing.protobuf.PersonDTO getHandicapper() {
    return handicapper_ == null ? org.seasailing.protobuf.PersonDTO.getDefaultInstance() : handicapper_;
  }
  /**
   * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
   */
  public org.seasailing.protobuf.PersonDTOOrBuilder getHandicapperOrBuilder() {
    return getHandicapper();
  }

  public static final int DEFAULTHANDICAP_FIELD_NUMBER = 5;
  private org.seasailing.protobuf.HandicapDTO defaultHandicap_;
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
   */
  public boolean hasDefaultHandicap() {
    return defaultHandicap_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
   */
  public org.seasailing.protobuf.HandicapDTO getDefaultHandicap() {
    return defaultHandicap_ == null ? org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : defaultHandicap_;
  }
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
   */
  public org.seasailing.protobuf.HandicapDTOOrBuilder getDefaultHandicapOrBuilder() {
    return getDefaultHandicap();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (name_ != null) {
      output.writeMessage(2, getName());
    }
    if (email_ != null) {
      output.writeMessage(3, getEmail());
    }
    if (handicapper_ != null) {
      output.writeMessage(4, getHandicapper());
    }
    if (defaultHandicap_ != null) {
      output.writeMessage(5, getDefaultHandicap());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getName());
    }
    if (email_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEmail());
    }
    if (handicapper_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getHandicapper());
    }
    if (defaultHandicap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDefaultHandicap());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.ClubDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.ClubDTO other = (org.seasailing.protobuf.ClubDTO) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && (hasName() == other.hasName());
    if (hasName()) {
      result = result && getName()
          .equals(other.getName());
    }
    result = result && (hasEmail() == other.hasEmail());
    if (hasEmail()) {
      result = result && getEmail()
          .equals(other.getEmail());
    }
    result = result && (hasHandicapper() == other.hasHandicapper());
    if (hasHandicapper()) {
      result = result && getHandicapper()
          .equals(other.getHandicapper());
    }
    result = result && (hasDefaultHandicap() == other.hasDefaultHandicap());
    if (hasDefaultHandicap()) {
      result = result && getDefaultHandicap()
          .equals(other.getDefaultHandicap());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasHandicapper()) {
      hash = (37 * hash) + HANDICAPPER_FIELD_NUMBER;
      hash = (53 * hash) + getHandicapper().hashCode();
    }
    if (hasDefaultHandicap()) {
      hash = (37 * hash) + DEFAULTHANDICAP_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultHandicap().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.ClubDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.ClubDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ClubDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ClubDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.ClubDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.ClubDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.ClubDTO)
      org.seasailing.protobuf.ClubDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ClubDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ClubDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.ClubDTO.class, org.seasailing.protobuf.ClubDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.ClubDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (emailBuilder_ == null) {
        email_ = null;
      } else {
        email_ = null;
        emailBuilder_ = null;
      }
      if (handicapperBuilder_ == null) {
        handicapper_ = null;
      } else {
        handicapper_ = null;
        handicapperBuilder_ = null;
      }
      if (defaultHandicapBuilder_ == null) {
        defaultHandicap_ = null;
      } else {
        defaultHandicap_ = null;
        defaultHandicapBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ClubDTO_descriptor;
    }

    public org.seasailing.protobuf.ClubDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.ClubDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.ClubDTO build() {
      org.seasailing.protobuf.ClubDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.ClubDTO buildPartial() {
      org.seasailing.protobuf.ClubDTO result = new org.seasailing.protobuf.ClubDTO(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (emailBuilder_ == null) {
        result.email_ = email_;
      } else {
        result.email_ = emailBuilder_.build();
      }
      if (handicapperBuilder_ == null) {
        result.handicapper_ = handicapper_;
      } else {
        result.handicapper_ = handicapperBuilder_.build();
      }
      if (defaultHandicapBuilder_ == null) {
        result.defaultHandicap_ = defaultHandicap_;
      } else {
        result.defaultHandicap_ = defaultHandicapBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.ClubDTO) {
        return mergeFrom((org.seasailing.protobuf.ClubDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.ClubDTO other) {
      if (other == org.seasailing.protobuf.ClubDTO.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasEmail()) {
        mergeEmail(other.getEmail());
      }
      if (other.hasHandicapper()) {
        mergeHandicapper(other.getHandicapper());
      }
      if (other.hasDefaultHandicap()) {
        mergeDefaultHandicap(other.getDefaultHandicap());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.ClubDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.ClubDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value id_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int32Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.StringValue name_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder mergeName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.StringValue email_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> emailBuilder_;
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public boolean hasEmail() {
      return emailBuilder_ != null || email_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public com.google.protobuf.StringValue getEmail() {
      if (emailBuilder_ == null) {
        return email_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : email_;
      } else {
        return emailBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public Builder setEmail(com.google.protobuf.StringValue value) {
      if (emailBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        email_ = value;
        onChanged();
      } else {
        emailBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public Builder setEmail(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (emailBuilder_ == null) {
        email_ = builderForValue.build();
        onChanged();
      } else {
        emailBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public Builder mergeEmail(com.google.protobuf.StringValue value) {
      if (emailBuilder_ == null) {
        if (email_ != null) {
          email_ =
            com.google.protobuf.StringValue.newBuilder(email_).mergeFrom(value).buildPartial();
        } else {
          email_ = value;
        }
        onChanged();
      } else {
        emailBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public Builder clearEmail() {
      if (emailBuilder_ == null) {
        email_ = null;
        onChanged();
      } else {
        email_ = null;
        emailBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getEmailBuilder() {
      
      onChanged();
      return getEmailFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getEmailOrBuilder() {
      if (emailBuilder_ != null) {
        return emailBuilder_.getMessageOrBuilder();
      } else {
        return email_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : email_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue email = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getEmailFieldBuilder() {
      if (emailBuilder_ == null) {
        emailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getEmail(),
                getParentForChildren(),
                isClean());
        email_ = null;
      }
      return emailBuilder_;
    }

    private org.seasailing.protobuf.PersonDTO handicapper_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder> handicapperBuilder_;
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public boolean hasHandicapper() {
      return handicapperBuilder_ != null || handicapper_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public org.seasailing.protobuf.PersonDTO getHandicapper() {
      if (handicapperBuilder_ == null) {
        return handicapper_ == null ? org.seasailing.protobuf.PersonDTO.getDefaultInstance() : handicapper_;
      } else {
        return handicapperBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public Builder setHandicapper(org.seasailing.protobuf.PersonDTO value) {
      if (handicapperBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        handicapper_ = value;
        onChanged();
      } else {
        handicapperBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public Builder setHandicapper(
        org.seasailing.protobuf.PersonDTO.Builder builderForValue) {
      if (handicapperBuilder_ == null) {
        handicapper_ = builderForValue.build();
        onChanged();
      } else {
        handicapperBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public Builder mergeHandicapper(org.seasailing.protobuf.PersonDTO value) {
      if (handicapperBuilder_ == null) {
        if (handicapper_ != null) {
          handicapper_ =
            org.seasailing.protobuf.PersonDTO.newBuilder(handicapper_).mergeFrom(value).buildPartial();
        } else {
          handicapper_ = value;
        }
        onChanged();
      } else {
        handicapperBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public Builder clearHandicapper() {
      if (handicapperBuilder_ == null) {
        handicapper_ = null;
        onChanged();
      } else {
        handicapper_ = null;
        handicapperBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public org.seasailing.protobuf.PersonDTO.Builder getHandicapperBuilder() {
      
      onChanged();
      return getHandicapperFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    public org.seasailing.protobuf.PersonDTOOrBuilder getHandicapperOrBuilder() {
      if (handicapperBuilder_ != null) {
        return handicapperBuilder_.getMessageOrBuilder();
      } else {
        return handicapper_ == null ?
            org.seasailing.protobuf.PersonDTO.getDefaultInstance() : handicapper_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.PersonDTO handicapper = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder> 
        getHandicapperFieldBuilder() {
      if (handicapperBuilder_ == null) {
        handicapperBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.PersonDTO, org.seasailing.protobuf.PersonDTO.Builder, org.seasailing.protobuf.PersonDTOOrBuilder>(
                getHandicapper(),
                getParentForChildren(),
                isClean());
        handicapper_ = null;
      }
      return handicapperBuilder_;
    }

    private org.seasailing.protobuf.HandicapDTO defaultHandicap_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder> defaultHandicapBuilder_;
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public boolean hasDefaultHandicap() {
      return defaultHandicapBuilder_ != null || defaultHandicap_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public org.seasailing.protobuf.HandicapDTO getDefaultHandicap() {
      if (defaultHandicapBuilder_ == null) {
        return defaultHandicap_ == null ? org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : defaultHandicap_;
      } else {
        return defaultHandicapBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public Builder setDefaultHandicap(org.seasailing.protobuf.HandicapDTO value) {
      if (defaultHandicapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        defaultHandicap_ = value;
        onChanged();
      } else {
        defaultHandicapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public Builder setDefaultHandicap(
        org.seasailing.protobuf.HandicapDTO.Builder builderForValue) {
      if (defaultHandicapBuilder_ == null) {
        defaultHandicap_ = builderForValue.build();
        onChanged();
      } else {
        defaultHandicapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public Builder mergeDefaultHandicap(org.seasailing.protobuf.HandicapDTO value) {
      if (defaultHandicapBuilder_ == null) {
        if (defaultHandicap_ != null) {
          defaultHandicap_ =
            org.seasailing.protobuf.HandicapDTO.newBuilder(defaultHandicap_).mergeFrom(value).buildPartial();
        } else {
          defaultHandicap_ = value;
        }
        onChanged();
      } else {
        defaultHandicapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public Builder clearDefaultHandicap() {
      if (defaultHandicapBuilder_ == null) {
        defaultHandicap_ = null;
        onChanged();
      } else {
        defaultHandicap_ = null;
        defaultHandicapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public org.seasailing.protobuf.HandicapDTO.Builder getDefaultHandicapBuilder() {
      
      onChanged();
      return getDefaultHandicapFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    public org.seasailing.protobuf.HandicapDTOOrBuilder getDefaultHandicapOrBuilder() {
      if (defaultHandicapBuilder_ != null) {
        return defaultHandicapBuilder_.getMessageOrBuilder();
      } else {
        return defaultHandicap_ == null ?
            org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : defaultHandicap_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO defaultHandicap = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder> 
        getDefaultHandicapFieldBuilder() {
      if (defaultHandicapBuilder_ == null) {
        defaultHandicapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder>(
                getDefaultHandicap(),
                getParentForChildren(),
                isClean());
        defaultHandicap_ = null;
      }
      return defaultHandicapBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.ClubDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.ClubDTO)
  private static final org.seasailing.protobuf.ClubDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.ClubDTO();
  }

  public static org.seasailing.protobuf.ClubDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClubDTO>
      PARSER = new com.google.protobuf.AbstractParser<ClubDTO>() {
    public ClubDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClubDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClubDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClubDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.ClubDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

