// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public interface CourseDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.CourseDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  com.google.protobuf.Int32Value getId();
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  boolean hasName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValue getName();
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getNameOrBuilder();

  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  boolean hasDescription();
  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  com.google.protobuf.StringValue getDescription();
  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue distance = 4;</code>
   */
  boolean hasDistance();
  /**
   * <code>.google.protobuf.DoubleValue distance = 4;</code>
   */
  com.google.protobuf.DoubleValue getDistance();
  /**
   * <code>.google.protobuf.DoubleValue distance = 4;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getDistanceOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 5;</code>
   */
  boolean hasClub();
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 5;</code>
   */
  org.seasailing.protobuf.ClubDTO getClub();
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 5;</code>
   */
  org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder();
}
