// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public interface FinishTimeDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.FinishTimeDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  boolean hasBoat();
  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  org.seasailing.protobuf.BoatDTO getBoat();
  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  org.seasailing.protobuf.BoatDTOOrBuilder getBoatOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.FinishTimeDTO.Status status = 2;</code>
   */
  int getStatusValue();
  /**
   * <code>.org.seasailing.protobuf.FinishTimeDTO.Status status = 2;</code>
   */
  org.seasailing.protobuf.FinishTimeDTO.Status getStatus();

  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 3;</code>
   */
  boolean hasElapsedTime();
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 3;</code>
   */
  com.google.protobuf.Int64Value getElapsedTime();
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 3;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getElapsedTimeOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value correctedTime = 4;</code>
   */
  boolean hasCorrectedTime();
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 4;</code>
   */
  com.google.protobuf.Int64Value getCorrectedTime();
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 4;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getCorrectedTimeOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.FinishRaceDTO race = 5;</code>
   */
  boolean hasRace();
  /**
   * <code>.org.seasailing.protobuf.FinishRaceDTO race = 5;</code>
   */
  org.seasailing.protobuf.FinishRaceDTO getRace();
  /**
   * <code>.org.seasailing.protobuf.FinishRaceDTO race = 5;</code>
   */
  org.seasailing.protobuf.FinishRaceDTOOrBuilder getRaceOrBuilder();
}
