// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.FinishTimeDTO}
 */
public  final class FinishTimeDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.FinishTimeDTO)
    FinishTimeDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FinishTimeDTO.newBuilder() to construct.
  private FinishTimeDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FinishTimeDTO() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FinishTimeDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.seasailing.protobuf.BoatDTO.Builder subBuilder = null;
            if (boat_ != null) {
              subBuilder = boat_.toBuilder();
            }
            boat_ = input.readMessage(org.seasailing.protobuf.BoatDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(boat_);
              boat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 26: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (finishTime_ != null) {
              subBuilder = finishTime_.toBuilder();
            }
            finishTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(finishTime_);
              finishTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.seasailing.protobuf.RaceDTO.Builder subBuilder = null;
            if (race_ != null) {
              subBuilder = race_.toBuilder();
            }
            race_ = input.readMessage(org.seasailing.protobuf.RaceDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(race_);
              race_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_FinishTimeDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.FinishTimeDTO.class, org.seasailing.protobuf.FinishTimeDTO.Builder.class);
  }

  public static final int BOAT_FIELD_NUMBER = 1;
  private org.seasailing.protobuf.BoatDTO boat_;
  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  public boolean hasBoat() {
    return boat_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  public org.seasailing.protobuf.BoatDTO getBoat() {
    return boat_ == null ? org.seasailing.protobuf.BoatDTO.getDefaultInstance() : boat_;
  }
  /**
   * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
   */
  public org.seasailing.protobuf.BoatDTOOrBuilder getBoatOrBuilder() {
    return getBoat();
  }

  public static final int STATUS_FIELD_NUMBER = 2;
  private int status_;
  /**
   * <code>.org.seasailing.protobuf.Status status = 2;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.org.seasailing.protobuf.Status status = 2;</code>
   */
  public org.seasailing.protobuf.Status getStatus() {
    org.seasailing.protobuf.Status result = org.seasailing.protobuf.Status.valueOf(status_);
    return result == null ? org.seasailing.protobuf.Status.UNRECOGNIZED : result;
  }

  public static final int FINISHTIME_FIELD_NUMBER = 3;
  private com.google.protobuf.Int64Value finishTime_;
  /**
   * <code>.google.protobuf.Int64Value finishTime = 3;</code>
   */
  public boolean hasFinishTime() {
    return finishTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value finishTime = 3;</code>
   */
  public com.google.protobuf.Int64Value getFinishTime() {
    return finishTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value finishTime = 3;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getFinishTimeOrBuilder() {
    return getFinishTime();
  }

  public static final int RACE_FIELD_NUMBER = 4;
  private org.seasailing.protobuf.RaceDTO race_;
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
   */
  public boolean hasRace() {
    return race_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
   */
  public org.seasailing.protobuf.RaceDTO getRace() {
    return race_ == null ? org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
  }
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
   */
  public org.seasailing.protobuf.RaceDTOOrBuilder getRaceOrBuilder() {
    return getRace();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (boat_ != null) {
      output.writeMessage(1, getBoat());
    }
    if (status_ != org.seasailing.protobuf.Status.FINISHED.getNumber()) {
      output.writeEnum(2, status_);
    }
    if (finishTime_ != null) {
      output.writeMessage(3, getFinishTime());
    }
    if (race_ != null) {
      output.writeMessage(4, getRace());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (boat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBoat());
    }
    if (status_ != org.seasailing.protobuf.Status.FINISHED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, status_);
    }
    if (finishTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getFinishTime());
    }
    if (race_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getRace());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.FinishTimeDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.FinishTimeDTO other = (org.seasailing.protobuf.FinishTimeDTO) obj;

    boolean result = true;
    result = result && (hasBoat() == other.hasBoat());
    if (hasBoat()) {
      result = result && getBoat()
          .equals(other.getBoat());
    }
    result = result && status_ == other.status_;
    result = result && (hasFinishTime() == other.hasFinishTime());
    if (hasFinishTime()) {
      result = result && getFinishTime()
          .equals(other.getFinishTime());
    }
    result = result && (hasRace() == other.hasRace());
    if (hasRace()) {
      result = result && getRace()
          .equals(other.getRace());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBoat()) {
      hash = (37 * hash) + BOAT_FIELD_NUMBER;
      hash = (53 * hash) + getBoat().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasFinishTime()) {
      hash = (37 * hash) + FINISHTIME_FIELD_NUMBER;
      hash = (53 * hash) + getFinishTime().hashCode();
    }
    if (hasRace()) {
      hash = (37 * hash) + RACE_FIELD_NUMBER;
      hash = (53 * hash) + getRace().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.FinishTimeDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.FinishTimeDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.FinishTimeDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.FinishTimeDTO)
      org.seasailing.protobuf.FinishTimeDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_FinishTimeDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.FinishTimeDTO.class, org.seasailing.protobuf.FinishTimeDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.FinishTimeDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (boatBuilder_ == null) {
        boat_ = null;
      } else {
        boat_ = null;
        boatBuilder_ = null;
      }
      status_ = 0;

      if (finishTimeBuilder_ == null) {
        finishTime_ = null;
      } else {
        finishTime_ = null;
        finishTimeBuilder_ = null;
      }
      if (raceBuilder_ == null) {
        race_ = null;
      } else {
        race_ = null;
        raceBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor;
    }

    public org.seasailing.protobuf.FinishTimeDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.FinishTimeDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.FinishTimeDTO build() {
      org.seasailing.protobuf.FinishTimeDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.FinishTimeDTO buildPartial() {
      org.seasailing.protobuf.FinishTimeDTO result = new org.seasailing.protobuf.FinishTimeDTO(this);
      if (boatBuilder_ == null) {
        result.boat_ = boat_;
      } else {
        result.boat_ = boatBuilder_.build();
      }
      result.status_ = status_;
      if (finishTimeBuilder_ == null) {
        result.finishTime_ = finishTime_;
      } else {
        result.finishTime_ = finishTimeBuilder_.build();
      }
      if (raceBuilder_ == null) {
        result.race_ = race_;
      } else {
        result.race_ = raceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.FinishTimeDTO) {
        return mergeFrom((org.seasailing.protobuf.FinishTimeDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.FinishTimeDTO other) {
      if (other == org.seasailing.protobuf.FinishTimeDTO.getDefaultInstance()) return this;
      if (other.hasBoat()) {
        mergeBoat(other.getBoat());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasFinishTime()) {
        mergeFinishTime(other.getFinishTime());
      }
      if (other.hasRace()) {
        mergeRace(other.getRace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.FinishTimeDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.FinishTimeDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.seasailing.protobuf.BoatDTO boat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.BoatDTO, org.seasailing.protobuf.BoatDTO.Builder, org.seasailing.protobuf.BoatDTOOrBuilder> boatBuilder_;
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public boolean hasBoat() {
      return boatBuilder_ != null || boat_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTO getBoat() {
      if (boatBuilder_ == null) {
        return boat_ == null ? org.seasailing.protobuf.BoatDTO.getDefaultInstance() : boat_;
      } else {
        return boatBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public Builder setBoat(org.seasailing.protobuf.BoatDTO value) {
      if (boatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        boat_ = value;
        onChanged();
      } else {
        boatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public Builder setBoat(
        org.seasailing.protobuf.BoatDTO.Builder builderForValue) {
      if (boatBuilder_ == null) {
        boat_ = builderForValue.build();
        onChanged();
      } else {
        boatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public Builder mergeBoat(org.seasailing.protobuf.BoatDTO value) {
      if (boatBuilder_ == null) {
        if (boat_ != null) {
          boat_ =
            org.seasailing.protobuf.BoatDTO.newBuilder(boat_).mergeFrom(value).buildPartial();
        } else {
          boat_ = value;
        }
        onChanged();
      } else {
        boatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public Builder clearBoat() {
      if (boatBuilder_ == null) {
        boat_ = null;
        onChanged();
      } else {
        boat_ = null;
        boatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTO.Builder getBoatBuilder() {
      
      onChanged();
      return getBoatFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    public org.seasailing.protobuf.BoatDTOOrBuilder getBoatOrBuilder() {
      if (boatBuilder_ != null) {
        return boatBuilder_.getMessageOrBuilder();
      } else {
        return boat_ == null ?
            org.seasailing.protobuf.BoatDTO.getDefaultInstance() : boat_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.BoatDTO boat = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.BoatDTO, org.seasailing.protobuf.BoatDTO.Builder, org.seasailing.protobuf.BoatDTOOrBuilder> 
        getBoatFieldBuilder() {
      if (boatBuilder_ == null) {
        boatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.BoatDTO, org.seasailing.protobuf.BoatDTO.Builder, org.seasailing.protobuf.BoatDTOOrBuilder>(
                getBoat(),
                getParentForChildren(),
                isClean());
        boat_ = null;
      }
      return boatBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.org.seasailing.protobuf.Status status = 2;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 2;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 2;</code>
     */
    public org.seasailing.protobuf.Status getStatus() {
      org.seasailing.protobuf.Status result = org.seasailing.protobuf.Status.valueOf(status_);
      return result == null ? org.seasailing.protobuf.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 2;</code>
     */
    public Builder setStatus(org.seasailing.protobuf.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 2;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value finishTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> finishTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public boolean hasFinishTime() {
      return finishTimeBuilder_ != null || finishTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public com.google.protobuf.Int64Value getFinishTime() {
      if (finishTimeBuilder_ == null) {
        return finishTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
      } else {
        return finishTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public Builder setFinishTime(com.google.protobuf.Int64Value value) {
      if (finishTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        finishTime_ = value;
        onChanged();
      } else {
        finishTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public Builder setFinishTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (finishTimeBuilder_ == null) {
        finishTime_ = builderForValue.build();
        onChanged();
      } else {
        finishTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public Builder mergeFinishTime(com.google.protobuf.Int64Value value) {
      if (finishTimeBuilder_ == null) {
        if (finishTime_ != null) {
          finishTime_ =
            com.google.protobuf.Int64Value.newBuilder(finishTime_).mergeFrom(value).buildPartial();
        } else {
          finishTime_ = value;
        }
        onChanged();
      } else {
        finishTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public Builder clearFinishTime() {
      if (finishTimeBuilder_ == null) {
        finishTime_ = null;
        onChanged();
      } else {
        finishTime_ = null;
        finishTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public com.google.protobuf.Int64Value.Builder getFinishTimeBuilder() {
      
      onChanged();
      return getFinishTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getFinishTimeOrBuilder() {
      if (finishTimeBuilder_ != null) {
        return finishTimeBuilder_.getMessageOrBuilder();
      } else {
        return finishTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getFinishTimeFieldBuilder() {
      if (finishTimeBuilder_ == null) {
        finishTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getFinishTime(),
                getParentForChildren(),
                isClean());
        finishTime_ = null;
      }
      return finishTimeBuilder_;
    }

    private org.seasailing.protobuf.RaceDTO race_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder> raceBuilder_;
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public boolean hasRace() {
      return raceBuilder_ != null || race_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public org.seasailing.protobuf.RaceDTO getRace() {
      if (raceBuilder_ == null) {
        return race_ == null ? org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
      } else {
        return raceBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public Builder setRace(org.seasailing.protobuf.RaceDTO value) {
      if (raceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        race_ = value;
        onChanged();
      } else {
        raceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public Builder setRace(
        org.seasailing.protobuf.RaceDTO.Builder builderForValue) {
      if (raceBuilder_ == null) {
        race_ = builderForValue.build();
        onChanged();
      } else {
        raceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public Builder mergeRace(org.seasailing.protobuf.RaceDTO value) {
      if (raceBuilder_ == null) {
        if (race_ != null) {
          race_ =
            org.seasailing.protobuf.RaceDTO.newBuilder(race_).mergeFrom(value).buildPartial();
        } else {
          race_ = value;
        }
        onChanged();
      } else {
        raceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public Builder clearRace() {
      if (raceBuilder_ == null) {
        race_ = null;
        onChanged();
      } else {
        race_ = null;
        raceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public org.seasailing.protobuf.RaceDTO.Builder getRaceBuilder() {
      
      onChanged();
      return getRaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    public org.seasailing.protobuf.RaceDTOOrBuilder getRaceOrBuilder() {
      if (raceBuilder_ != null) {
        return raceBuilder_.getMessageOrBuilder();
      } else {
        return race_ == null ?
            org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder> 
        getRaceFieldBuilder() {
      if (raceBuilder_ == null) {
        raceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder>(
                getRace(),
                getParentForChildren(),
                isClean());
        race_ = null;
      }
      return raceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.FinishTimeDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.FinishTimeDTO)
  private static final org.seasailing.protobuf.FinishTimeDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.FinishTimeDTO();
  }

  public static org.seasailing.protobuf.FinishTimeDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FinishTimeDTO>
      PARSER = new com.google.protobuf.AbstractParser<FinishTimeDTO>() {
    public FinishTimeDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FinishTimeDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FinishTimeDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FinishTimeDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.FinishTimeDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

