// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public interface HandicapDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.HandicapDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  boolean hasDenominator();
  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  com.google.protobuf.Int32Value getDenominator();
  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getDenominatorOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
   */
  int getMethodValue();
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
   */
  org.seasailing.protobuf.HandicapDTO.Method getMethod();
}
