// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.HandicapDTO}
 */
public  final class HandicapDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.HandicapDTO)
    HandicapDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HandicapDTO.newBuilder() to construct.
  private HandicapDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HandicapDTO() {
    method_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HandicapDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (denominator_ != null) {
              subBuilder = denominator_.toBuilder();
            }
            denominator_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(denominator_);
              denominator_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            method_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_HandicapDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_HandicapDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.HandicapDTO.class, org.seasailing.protobuf.HandicapDTO.Builder.class);
  }

  /**
   * Protobuf enum {@code org.seasailing.protobuf.HandicapDTO.Method}
   */
  public enum Method
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TIME_ON_TIME = 0;</code>
     */
    TIME_ON_TIME(0),
    /**
     * <code>TIME_ON_DISTANCE = 1;</code>
     */
    TIME_ON_DISTANCE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TIME_ON_TIME = 0;</code>
     */
    public static final int TIME_ON_TIME_VALUE = 0;
    /**
     * <code>TIME_ON_DISTANCE = 1;</code>
     */
    public static final int TIME_ON_DISTANCE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Method valueOf(int value) {
      return forNumber(value);
    }

    public static Method forNumber(int value) {
      switch (value) {
        case 0: return TIME_ON_TIME;
        case 1: return TIME_ON_DISTANCE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Method>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Method> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Method>() {
            public Method findValueByNumber(int number) {
              return Method.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.seasailing.protobuf.HandicapDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final Method[] VALUES = values();

    public static Method valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Method(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.seasailing.protobuf.HandicapDTO.Method)
  }

  public static final int DENOMINATOR_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value denominator_;
  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  public boolean hasDenominator() {
    return denominator_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  public com.google.protobuf.Int32Value getDenominator() {
    return denominator_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : denominator_;
  }
  /**
   * <code>.google.protobuf.Int32Value denominator = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getDenominatorOrBuilder() {
    return getDenominator();
  }

  public static final int METHOD_FIELD_NUMBER = 4;
  private int method_;
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
   */
  public int getMethodValue() {
    return method_;
  }
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
   */
  public org.seasailing.protobuf.HandicapDTO.Method getMethod() {
    org.seasailing.protobuf.HandicapDTO.Method result = org.seasailing.protobuf.HandicapDTO.Method.valueOf(method_);
    return result == null ? org.seasailing.protobuf.HandicapDTO.Method.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (denominator_ != null) {
      output.writeMessage(1, getDenominator());
    }
    if (method_ != org.seasailing.protobuf.HandicapDTO.Method.TIME_ON_TIME.getNumber()) {
      output.writeEnum(4, method_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (denominator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDenominator());
    }
    if (method_ != org.seasailing.protobuf.HandicapDTO.Method.TIME_ON_TIME.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, method_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.HandicapDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.HandicapDTO other = (org.seasailing.protobuf.HandicapDTO) obj;

    boolean result = true;
    result = result && (hasDenominator() == other.hasDenominator());
    if (hasDenominator()) {
      result = result && getDenominator()
          .equals(other.getDenominator());
    }
    result = result && method_ == other.method_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDenominator()) {
      hash = (37 * hash) + DENOMINATOR_FIELD_NUMBER;
      hash = (53 * hash) + getDenominator().hashCode();
    }
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + method_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.HandicapDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.HandicapDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.HandicapDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.HandicapDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.HandicapDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.HandicapDTO)
      org.seasailing.protobuf.HandicapDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_HandicapDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_HandicapDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.HandicapDTO.class, org.seasailing.protobuf.HandicapDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.HandicapDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (denominatorBuilder_ == null) {
        denominator_ = null;
      } else {
        denominator_ = null;
        denominatorBuilder_ = null;
      }
      method_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_HandicapDTO_descriptor;
    }

    public org.seasailing.protobuf.HandicapDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.HandicapDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.HandicapDTO build() {
      org.seasailing.protobuf.HandicapDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.HandicapDTO buildPartial() {
      org.seasailing.protobuf.HandicapDTO result = new org.seasailing.protobuf.HandicapDTO(this);
      if (denominatorBuilder_ == null) {
        result.denominator_ = denominator_;
      } else {
        result.denominator_ = denominatorBuilder_.build();
      }
      result.method_ = method_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.HandicapDTO) {
        return mergeFrom((org.seasailing.protobuf.HandicapDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.HandicapDTO other) {
      if (other == org.seasailing.protobuf.HandicapDTO.getDefaultInstance()) return this;
      if (other.hasDenominator()) {
        mergeDenominator(other.getDenominator());
      }
      if (other.method_ != 0) {
        setMethodValue(other.getMethodValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.HandicapDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.HandicapDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value denominator_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> denominatorBuilder_;
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public boolean hasDenominator() {
      return denominatorBuilder_ != null || denominator_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public com.google.protobuf.Int32Value getDenominator() {
      if (denominatorBuilder_ == null) {
        return denominator_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : denominator_;
      } else {
        return denominatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public Builder setDenominator(com.google.protobuf.Int32Value value) {
      if (denominatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        denominator_ = value;
        onChanged();
      } else {
        denominatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public Builder setDenominator(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (denominatorBuilder_ == null) {
        denominator_ = builderForValue.build();
        onChanged();
      } else {
        denominatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public Builder mergeDenominator(com.google.protobuf.Int32Value value) {
      if (denominatorBuilder_ == null) {
        if (denominator_ != null) {
          denominator_ =
            com.google.protobuf.Int32Value.newBuilder(denominator_).mergeFrom(value).buildPartial();
        } else {
          denominator_ = value;
        }
        onChanged();
      } else {
        denominatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public Builder clearDenominator() {
      if (denominatorBuilder_ == null) {
        denominator_ = null;
        onChanged();
      } else {
        denominator_ = null;
        denominatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getDenominatorBuilder() {
      
      onChanged();
      return getDenominatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getDenominatorOrBuilder() {
      if (denominatorBuilder_ != null) {
        return denominatorBuilder_.getMessageOrBuilder();
      } else {
        return denominator_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : denominator_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value denominator = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getDenominatorFieldBuilder() {
      if (denominatorBuilder_ == null) {
        denominatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getDenominator(),
                getParentForChildren(),
                isClean());
        denominator_ = null;
      }
      return denominatorBuilder_;
    }

    private int method_ = 0;
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
     */
    public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
     */
    public Builder setMethodValue(int value) {
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
     */
    public org.seasailing.protobuf.HandicapDTO.Method getMethod() {
      org.seasailing.protobuf.HandicapDTO.Method result = org.seasailing.protobuf.HandicapDTO.Method.valueOf(method_);
      return result == null ? org.seasailing.protobuf.HandicapDTO.Method.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
     */
    public Builder setMethod(org.seasailing.protobuf.HandicapDTO.Method value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      method_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO.Method method = 4;</code>
     */
    public Builder clearMethod() {
      
      method_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.HandicapDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.HandicapDTO)
  private static final org.seasailing.protobuf.HandicapDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.HandicapDTO();
  }

  public static org.seasailing.protobuf.HandicapDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HandicapDTO>
      PARSER = new com.google.protobuf.AbstractParser<HandicapDTO>() {
    public HandicapDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HandicapDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HandicapDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HandicapDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.HandicapDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

