// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.RaceDTO}
 */
public  final class RaceDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.RaceDTO)
    RaceDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RaceDTO.newBuilder() to construct.
  private RaceDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RaceDTO() {
    option_ = 0;
    results_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RaceDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (startTime_ != null) {
              subBuilder = startTime_.toBuilder();
            }
            startTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startTime_);
              startTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            org.seasailing.protobuf.SeriesDTO.Builder subBuilder = null;
            if (series_ != null) {
              subBuilder = series_.toBuilder();
            }
            series_ = input.readMessage(org.seasailing.protobuf.SeriesDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(series_);
              series_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.seasailing.protobuf.CourseDTO.Builder subBuilder = null;
            if (course_ != null) {
              subBuilder = course_.toBuilder();
            }
            course_ = input.readMessage(org.seasailing.protobuf.CourseDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(course_);
              course_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (multiplier_ != null) {
              subBuilder = multiplier_.toBuilder();
            }
            multiplier_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(multiplier_);
              multiplier_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            option_ = rawValue;
            break;
          }
          case 58: {
            org.seasailing.protobuf.HandicapDTO.Builder subBuilder = null;
            if (handicap_ != null) {
              subBuilder = handicap_.toBuilder();
            }
            handicap_ = input.readMessage(org.seasailing.protobuf.HandicapDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(handicap_);
              handicap_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              results_ = new java.util.ArrayList<org.seasailing.protobuf.ResultDTO>();
              mutable_bitField0_ |= 0x00000080;
            }
            results_.add(
                input.readMessage(org.seasailing.protobuf.ResultDTO.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_RaceDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_RaceDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.RaceDTO.class, org.seasailing.protobuf.RaceDTO.Builder.class);
  }

  /**
   * Protobuf enum {@code org.seasailing.protobuf.RaceDTO.Option}
   */
  public enum Option
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DEFAULT = 0;</code>
     */
    DEFAULT(0),
    /**
     * <code>TWICE = 1;</code>
     */
    TWICE(1),
    /**
     * <code>REVERSE = 2;</code>
     */
    REVERSE(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>DEFAULT = 0;</code>
     */
    public static final int DEFAULT_VALUE = 0;
    /**
     * <code>TWICE = 1;</code>
     */
    public static final int TWICE_VALUE = 1;
    /**
     * <code>REVERSE = 2;</code>
     */
    public static final int REVERSE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Option valueOf(int value) {
      return forNumber(value);
    }

    public static Option forNumber(int value) {
      switch (value) {
        case 0: return DEFAULT;
        case 1: return TWICE;
        case 2: return REVERSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Option>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Option> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Option>() {
            public Option findValueByNumber(int number) {
              return Option.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.seasailing.protobuf.RaceDTO.getDescriptor().getEnumTypes().get(0);
    }

    private static final Option[] VALUES = values();

    public static Option valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Option(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.seasailing.protobuf.RaceDTO.Option)
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value id_;
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32Value getId() {
    return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int STARTTIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Int64Value startTime_;
  /**
   * <code>.google.protobuf.Int64Value startTime = 2;</code>
   */
  public boolean hasStartTime() {
    return startTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value startTime = 2;</code>
   */
  public com.google.protobuf.Int64Value getStartTime() {
    return startTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value startTime = 2;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getStartTimeOrBuilder() {
    return getStartTime();
  }

  public static final int SERIES_FIELD_NUMBER = 3;
  private org.seasailing.protobuf.SeriesDTO series_;
  /**
   * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
   */
  public boolean hasSeries() {
    return series_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
   */
  public org.seasailing.protobuf.SeriesDTO getSeries() {
    return series_ == null ? org.seasailing.protobuf.SeriesDTO.getDefaultInstance() : series_;
  }
  /**
   * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
   */
  public org.seasailing.protobuf.SeriesDTOOrBuilder getSeriesOrBuilder() {
    return getSeries();
  }

  public static final int COURSE_FIELD_NUMBER = 4;
  private org.seasailing.protobuf.CourseDTO course_;
  /**
   * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
   */
  public boolean hasCourse() {
    return course_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
   */
  public org.seasailing.protobuf.CourseDTO getCourse() {
    return course_ == null ? org.seasailing.protobuf.CourseDTO.getDefaultInstance() : course_;
  }
  /**
   * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
   */
  public org.seasailing.protobuf.CourseDTOOrBuilder getCourseOrBuilder() {
    return getCourse();
  }

  public static final int MULTIPLIER_FIELD_NUMBER = 5;
  private com.google.protobuf.Int32Value multiplier_;
  /**
   * <code>.google.protobuf.Int32Value multiplier = 5;</code>
   */
  public boolean hasMultiplier() {
    return multiplier_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value multiplier = 5;</code>
   */
  public com.google.protobuf.Int32Value getMultiplier() {
    return multiplier_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : multiplier_;
  }
  /**
   * <code>.google.protobuf.Int32Value multiplier = 5;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getMultiplierOrBuilder() {
    return getMultiplier();
  }

  public static final int OPTION_FIELD_NUMBER = 6;
  private int option_;
  /**
   * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
   */
  public int getOptionValue() {
    return option_;
  }
  /**
   * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
   */
  public org.seasailing.protobuf.RaceDTO.Option getOption() {
    org.seasailing.protobuf.RaceDTO.Option result = org.seasailing.protobuf.RaceDTO.Option.valueOf(option_);
    return result == null ? org.seasailing.protobuf.RaceDTO.Option.UNRECOGNIZED : result;
  }

  public static final int HANDICAP_FIELD_NUMBER = 7;
  private org.seasailing.protobuf.HandicapDTO handicap_;
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
   */
  public boolean hasHandicap() {
    return handicap_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
   */
  public org.seasailing.protobuf.HandicapDTO getHandicap() {
    return handicap_ == null ? org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : handicap_;
  }
  /**
   * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
   */
  public org.seasailing.protobuf.HandicapDTOOrBuilder getHandicapOrBuilder() {
    return getHandicap();
  }

  public static final int RESULTS_FIELD_NUMBER = 8;
  private java.util.List<org.seasailing.protobuf.ResultDTO> results_;
  /**
   * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
   */
  public java.util.List<org.seasailing.protobuf.ResultDTO> getResultsList() {
    return results_;
  }
  /**
   * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
   */
  public java.util.List<? extends org.seasailing.protobuf.ResultDTOOrBuilder> 
      getResultsOrBuilderList() {
    return results_;
  }
  /**
   * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
   */
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
   */
  public org.seasailing.protobuf.ResultDTO getResults(int index) {
    return results_.get(index);
  }
  /**
   * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
   */
  public org.seasailing.protobuf.ResultDTOOrBuilder getResultsOrBuilder(
      int index) {
    return results_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (startTime_ != null) {
      output.writeMessage(2, getStartTime());
    }
    if (series_ != null) {
      output.writeMessage(3, getSeries());
    }
    if (course_ != null) {
      output.writeMessage(4, getCourse());
    }
    if (multiplier_ != null) {
      output.writeMessage(5, getMultiplier());
    }
    if (option_ != org.seasailing.protobuf.RaceDTO.Option.DEFAULT.getNumber()) {
      output.writeEnum(6, option_);
    }
    if (handicap_ != null) {
      output.writeMessage(7, getHandicap());
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeMessage(8, results_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (startTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStartTime());
    }
    if (series_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSeries());
    }
    if (course_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCourse());
    }
    if (multiplier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getMultiplier());
    }
    if (option_ != org.seasailing.protobuf.RaceDTO.Option.DEFAULT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, option_);
    }
    if (handicap_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getHandicap());
    }
    for (int i = 0; i < results_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, results_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.RaceDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.RaceDTO other = (org.seasailing.protobuf.RaceDTO) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && (hasStartTime() == other.hasStartTime());
    if (hasStartTime()) {
      result = result && getStartTime()
          .equals(other.getStartTime());
    }
    result = result && (hasSeries() == other.hasSeries());
    if (hasSeries()) {
      result = result && getSeries()
          .equals(other.getSeries());
    }
    result = result && (hasCourse() == other.hasCourse());
    if (hasCourse()) {
      result = result && getCourse()
          .equals(other.getCourse());
    }
    result = result && (hasMultiplier() == other.hasMultiplier());
    if (hasMultiplier()) {
      result = result && getMultiplier()
          .equals(other.getMultiplier());
    }
    result = result && option_ == other.option_;
    result = result && (hasHandicap() == other.hasHandicap());
    if (hasHandicap()) {
      result = result && getHandicap()
          .equals(other.getHandicap());
    }
    result = result && getResultsList()
        .equals(other.getResultsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasStartTime()) {
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
    }
    if (hasSeries()) {
      hash = (37 * hash) + SERIES_FIELD_NUMBER;
      hash = (53 * hash) + getSeries().hashCode();
    }
    if (hasCourse()) {
      hash = (37 * hash) + COURSE_FIELD_NUMBER;
      hash = (53 * hash) + getCourse().hashCode();
    }
    if (hasMultiplier()) {
      hash = (37 * hash) + MULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + getMultiplier().hashCode();
    }
    hash = (37 * hash) + OPTION_FIELD_NUMBER;
    hash = (53 * hash) + option_;
    if (hasHandicap()) {
      hash = (37 * hash) + HANDICAP_FIELD_NUMBER;
      hash = (53 * hash) + getHandicap().hashCode();
    }
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.RaceDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.RaceDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.RaceDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.RaceDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.RaceDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.RaceDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.RaceDTO)
      org.seasailing.protobuf.RaceDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_RaceDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_RaceDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.RaceDTO.class, org.seasailing.protobuf.RaceDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.RaceDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (startTimeBuilder_ == null) {
        startTime_ = null;
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }
      if (seriesBuilder_ == null) {
        series_ = null;
      } else {
        series_ = null;
        seriesBuilder_ = null;
      }
      if (courseBuilder_ == null) {
        course_ = null;
      } else {
        course_ = null;
        courseBuilder_ = null;
      }
      if (multiplierBuilder_ == null) {
        multiplier_ = null;
      } else {
        multiplier_ = null;
        multiplierBuilder_ = null;
      }
      option_ = 0;

      if (handicapBuilder_ == null) {
        handicap_ = null;
      } else {
        handicap_ = null;
        handicapBuilder_ = null;
      }
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_RaceDTO_descriptor;
    }

    public org.seasailing.protobuf.RaceDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.RaceDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.RaceDTO build() {
      org.seasailing.protobuf.RaceDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.RaceDTO buildPartial() {
      org.seasailing.protobuf.RaceDTO result = new org.seasailing.protobuf.RaceDTO(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (startTimeBuilder_ == null) {
        result.startTime_ = startTime_;
      } else {
        result.startTime_ = startTimeBuilder_.build();
      }
      if (seriesBuilder_ == null) {
        result.series_ = series_;
      } else {
        result.series_ = seriesBuilder_.build();
      }
      if (courseBuilder_ == null) {
        result.course_ = course_;
      } else {
        result.course_ = courseBuilder_.build();
      }
      if (multiplierBuilder_ == null) {
        result.multiplier_ = multiplier_;
      } else {
        result.multiplier_ = multiplierBuilder_.build();
      }
      result.option_ = option_;
      if (handicapBuilder_ == null) {
        result.handicap_ = handicap_;
      } else {
        result.handicap_ = handicapBuilder_.build();
      }
      if (resultsBuilder_ == null) {
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          results_ = java.util.Collections.unmodifiableList(results_);
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.results_ = results_;
      } else {
        result.results_ = resultsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.RaceDTO) {
        return mergeFrom((org.seasailing.protobuf.RaceDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.RaceDTO other) {
      if (other == org.seasailing.protobuf.RaceDTO.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasStartTime()) {
        mergeStartTime(other.getStartTime());
      }
      if (other.hasSeries()) {
        mergeSeries(other.getSeries());
      }
      if (other.hasCourse()) {
        mergeCourse(other.getCourse());
      }
      if (other.hasMultiplier()) {
        mergeMultiplier(other.getMultiplier());
      }
      if (other.option_ != 0) {
        setOptionValue(other.getOptionValue());
      }
      if (other.hasHandicap()) {
        mergeHandicap(other.getHandicap());
      }
      if (resultsBuilder_ == null) {
        if (!other.results_.isEmpty()) {
          if (results_.isEmpty()) {
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureResultsIsMutable();
            results_.addAll(other.results_);
          }
          onChanged();
        }
      } else {
        if (!other.results_.isEmpty()) {
          if (resultsBuilder_.isEmpty()) {
            resultsBuilder_.dispose();
            resultsBuilder_ = null;
            results_ = other.results_;
            bitField0_ = (bitField0_ & ~0x00000080);
            resultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultsFieldBuilder() : null;
          } else {
            resultsBuilder_.addAllMessages(other.results_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.RaceDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.RaceDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Int32Value id_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int32Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.Int64Value startTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> startTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public boolean hasStartTime() {
      return startTimeBuilder_ != null || startTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public com.google.protobuf.Int64Value getStartTime() {
      if (startTimeBuilder_ == null) {
        return startTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
      } else {
        return startTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public Builder setStartTime(com.google.protobuf.Int64Value value) {
      if (startTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startTime_ = value;
        onChanged();
      } else {
        startTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public Builder setStartTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (startTimeBuilder_ == null) {
        startTime_ = builderForValue.build();
        onChanged();
      } else {
        startTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public Builder mergeStartTime(com.google.protobuf.Int64Value value) {
      if (startTimeBuilder_ == null) {
        if (startTime_ != null) {
          startTime_ =
            com.google.protobuf.Int64Value.newBuilder(startTime_).mergeFrom(value).buildPartial();
        } else {
          startTime_ = value;
        }
        onChanged();
      } else {
        startTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public Builder clearStartTime() {
      if (startTimeBuilder_ == null) {
        startTime_ = null;
        onChanged();
      } else {
        startTime_ = null;
        startTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public com.google.protobuf.Int64Value.Builder getStartTimeBuilder() {
      
      onChanged();
      return getStartTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getStartTimeOrBuilder() {
      if (startTimeBuilder_ != null) {
        return startTimeBuilder_.getMessageOrBuilder();
      } else {
        return startTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : startTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value startTime = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getStartTimeFieldBuilder() {
      if (startTimeBuilder_ == null) {
        startTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getStartTime(),
                getParentForChildren(),
                isClean());
        startTime_ = null;
      }
      return startTimeBuilder_;
    }

    private org.seasailing.protobuf.SeriesDTO series_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.SeriesDTO, org.seasailing.protobuf.SeriesDTO.Builder, org.seasailing.protobuf.SeriesDTOOrBuilder> seriesBuilder_;
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public boolean hasSeries() {
      return seriesBuilder_ != null || series_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public org.seasailing.protobuf.SeriesDTO getSeries() {
      if (seriesBuilder_ == null) {
        return series_ == null ? org.seasailing.protobuf.SeriesDTO.getDefaultInstance() : series_;
      } else {
        return seriesBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public Builder setSeries(org.seasailing.protobuf.SeriesDTO value) {
      if (seriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        series_ = value;
        onChanged();
      } else {
        seriesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public Builder setSeries(
        org.seasailing.protobuf.SeriesDTO.Builder builderForValue) {
      if (seriesBuilder_ == null) {
        series_ = builderForValue.build();
        onChanged();
      } else {
        seriesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public Builder mergeSeries(org.seasailing.protobuf.SeriesDTO value) {
      if (seriesBuilder_ == null) {
        if (series_ != null) {
          series_ =
            org.seasailing.protobuf.SeriesDTO.newBuilder(series_).mergeFrom(value).buildPartial();
        } else {
          series_ = value;
        }
        onChanged();
      } else {
        seriesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public Builder clearSeries() {
      if (seriesBuilder_ == null) {
        series_ = null;
        onChanged();
      } else {
        series_ = null;
        seriesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public org.seasailing.protobuf.SeriesDTO.Builder getSeriesBuilder() {
      
      onChanged();
      return getSeriesFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    public org.seasailing.protobuf.SeriesDTOOrBuilder getSeriesOrBuilder() {
      if (seriesBuilder_ != null) {
        return seriesBuilder_.getMessageOrBuilder();
      } else {
        return series_ == null ?
            org.seasailing.protobuf.SeriesDTO.getDefaultInstance() : series_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.SeriesDTO series = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.SeriesDTO, org.seasailing.protobuf.SeriesDTO.Builder, org.seasailing.protobuf.SeriesDTOOrBuilder> 
        getSeriesFieldBuilder() {
      if (seriesBuilder_ == null) {
        seriesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.SeriesDTO, org.seasailing.protobuf.SeriesDTO.Builder, org.seasailing.protobuf.SeriesDTOOrBuilder>(
                getSeries(),
                getParentForChildren(),
                isClean());
        series_ = null;
      }
      return seriesBuilder_;
    }

    private org.seasailing.protobuf.CourseDTO course_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.CourseDTO, org.seasailing.protobuf.CourseDTO.Builder, org.seasailing.protobuf.CourseDTOOrBuilder> courseBuilder_;
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public boolean hasCourse() {
      return courseBuilder_ != null || course_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public org.seasailing.protobuf.CourseDTO getCourse() {
      if (courseBuilder_ == null) {
        return course_ == null ? org.seasailing.protobuf.CourseDTO.getDefaultInstance() : course_;
      } else {
        return courseBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public Builder setCourse(org.seasailing.protobuf.CourseDTO value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        course_ = value;
        onChanged();
      } else {
        courseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public Builder setCourse(
        org.seasailing.protobuf.CourseDTO.Builder builderForValue) {
      if (courseBuilder_ == null) {
        course_ = builderForValue.build();
        onChanged();
      } else {
        courseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public Builder mergeCourse(org.seasailing.protobuf.CourseDTO value) {
      if (courseBuilder_ == null) {
        if (course_ != null) {
          course_ =
            org.seasailing.protobuf.CourseDTO.newBuilder(course_).mergeFrom(value).buildPartial();
        } else {
          course_ = value;
        }
        onChanged();
      } else {
        courseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public Builder clearCourse() {
      if (courseBuilder_ == null) {
        course_ = null;
        onChanged();
      } else {
        course_ = null;
        courseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public org.seasailing.protobuf.CourseDTO.Builder getCourseBuilder() {
      
      onChanged();
      return getCourseFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    public org.seasailing.protobuf.CourseDTOOrBuilder getCourseOrBuilder() {
      if (courseBuilder_ != null) {
        return courseBuilder_.getMessageOrBuilder();
      } else {
        return course_ == null ?
            org.seasailing.protobuf.CourseDTO.getDefaultInstance() : course_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.CourseDTO course = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.CourseDTO, org.seasailing.protobuf.CourseDTO.Builder, org.seasailing.protobuf.CourseDTOOrBuilder> 
        getCourseFieldBuilder() {
      if (courseBuilder_ == null) {
        courseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.CourseDTO, org.seasailing.protobuf.CourseDTO.Builder, org.seasailing.protobuf.CourseDTOOrBuilder>(
                getCourse(),
                getParentForChildren(),
                isClean());
        course_ = null;
      }
      return courseBuilder_;
    }

    private com.google.protobuf.Int32Value multiplier_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> multiplierBuilder_;
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public boolean hasMultiplier() {
      return multiplierBuilder_ != null || multiplier_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public com.google.protobuf.Int32Value getMultiplier() {
      if (multiplierBuilder_ == null) {
        return multiplier_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : multiplier_;
      } else {
        return multiplierBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public Builder setMultiplier(com.google.protobuf.Int32Value value) {
      if (multiplierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        multiplier_ = value;
        onChanged();
      } else {
        multiplierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public Builder setMultiplier(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (multiplierBuilder_ == null) {
        multiplier_ = builderForValue.build();
        onChanged();
      } else {
        multiplierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public Builder mergeMultiplier(com.google.protobuf.Int32Value value) {
      if (multiplierBuilder_ == null) {
        if (multiplier_ != null) {
          multiplier_ =
            com.google.protobuf.Int32Value.newBuilder(multiplier_).mergeFrom(value).buildPartial();
        } else {
          multiplier_ = value;
        }
        onChanged();
      } else {
        multiplierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public Builder clearMultiplier() {
      if (multiplierBuilder_ == null) {
        multiplier_ = null;
        onChanged();
      } else {
        multiplier_ = null;
        multiplierBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public com.google.protobuf.Int32Value.Builder getMultiplierBuilder() {
      
      onChanged();
      return getMultiplierFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getMultiplierOrBuilder() {
      if (multiplierBuilder_ != null) {
        return multiplierBuilder_.getMessageOrBuilder();
      } else {
        return multiplier_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : multiplier_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value multiplier = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getMultiplierFieldBuilder() {
      if (multiplierBuilder_ == null) {
        multiplierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getMultiplier(),
                getParentForChildren(),
                isClean());
        multiplier_ = null;
      }
      return multiplierBuilder_;
    }

    private int option_ = 0;
    /**
     * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
     */
    public int getOptionValue() {
      return option_;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
     */
    public Builder setOptionValue(int value) {
      option_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
     */
    public org.seasailing.protobuf.RaceDTO.Option getOption() {
      org.seasailing.protobuf.RaceDTO.Option result = org.seasailing.protobuf.RaceDTO.Option.valueOf(option_);
      return result == null ? org.seasailing.protobuf.RaceDTO.Option.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
     */
    public Builder setOption(org.seasailing.protobuf.RaceDTO.Option value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      option_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO.Option option = 6;</code>
     */
    public Builder clearOption() {
      
      option_ = 0;
      onChanged();
      return this;
    }

    private org.seasailing.protobuf.HandicapDTO handicap_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder> handicapBuilder_;
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public boolean hasHandicap() {
      return handicapBuilder_ != null || handicap_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public org.seasailing.protobuf.HandicapDTO getHandicap() {
      if (handicapBuilder_ == null) {
        return handicap_ == null ? org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : handicap_;
      } else {
        return handicapBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public Builder setHandicap(org.seasailing.protobuf.HandicapDTO value) {
      if (handicapBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        handicap_ = value;
        onChanged();
      } else {
        handicapBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public Builder setHandicap(
        org.seasailing.protobuf.HandicapDTO.Builder builderForValue) {
      if (handicapBuilder_ == null) {
        handicap_ = builderForValue.build();
        onChanged();
      } else {
        handicapBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public Builder mergeHandicap(org.seasailing.protobuf.HandicapDTO value) {
      if (handicapBuilder_ == null) {
        if (handicap_ != null) {
          handicap_ =
            org.seasailing.protobuf.HandicapDTO.newBuilder(handicap_).mergeFrom(value).buildPartial();
        } else {
          handicap_ = value;
        }
        onChanged();
      } else {
        handicapBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public Builder clearHandicap() {
      if (handicapBuilder_ == null) {
        handicap_ = null;
        onChanged();
      } else {
        handicap_ = null;
        handicapBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public org.seasailing.protobuf.HandicapDTO.Builder getHandicapBuilder() {
      
      onChanged();
      return getHandicapFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    public org.seasailing.protobuf.HandicapDTOOrBuilder getHandicapOrBuilder() {
      if (handicapBuilder_ != null) {
        return handicapBuilder_.getMessageOrBuilder();
      } else {
        return handicap_ == null ?
            org.seasailing.protobuf.HandicapDTO.getDefaultInstance() : handicap_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.HandicapDTO handicap = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder> 
        getHandicapFieldBuilder() {
      if (handicapBuilder_ == null) {
        handicapBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.HandicapDTO, org.seasailing.protobuf.HandicapDTO.Builder, org.seasailing.protobuf.HandicapDTOOrBuilder>(
                getHandicap(),
                getParentForChildren(),
                isClean());
        handicap_ = null;
      }
      return handicapBuilder_;
    }

    private java.util.List<org.seasailing.protobuf.ResultDTO> results_ =
      java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        results_ = new java.util.ArrayList<org.seasailing.protobuf.ResultDTO>(results_);
        bitField0_ |= 0x00000080;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.seasailing.protobuf.ResultDTO, org.seasailing.protobuf.ResultDTO.Builder, org.seasailing.protobuf.ResultDTOOrBuilder> resultsBuilder_;

    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public java.util.List<org.seasailing.protobuf.ResultDTO> getResultsList() {
      if (resultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(results_);
      } else {
        return resultsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public int getResultsCount() {
      if (resultsBuilder_ == null) {
        return results_.size();
      } else {
        return resultsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public org.seasailing.protobuf.ResultDTO getResults(int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);
      } else {
        return resultsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder setResults(
        int index, org.seasailing.protobuf.ResultDTO value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.set(index, value);
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder setResults(
        int index, org.seasailing.protobuf.ResultDTO.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder addResults(org.seasailing.protobuf.ResultDTO value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder addResults(
        int index, org.seasailing.protobuf.ResultDTO value) {
      if (resultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultsIsMutable();
        results_.add(index, value);
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder addResults(
        org.seasailing.protobuf.ResultDTO.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder addResults(
        int index, org.seasailing.protobuf.ResultDTO.Builder builderForValue) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends org.seasailing.protobuf.ResultDTO> values) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, results_);
        onChanged();
      } else {
        resultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder clearResults() {
      if (resultsBuilder_ == null) {
        results_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
      } else {
        resultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public Builder removeResults(int index) {
      if (resultsBuilder_ == null) {
        ensureResultsIsMutable();
        results_.remove(index);
        onChanged();
      } else {
        resultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public org.seasailing.protobuf.ResultDTO.Builder getResultsBuilder(
        int index) {
      return getResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public org.seasailing.protobuf.ResultDTOOrBuilder getResultsOrBuilder(
        int index) {
      if (resultsBuilder_ == null) {
        return results_.get(index);  } else {
        return resultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public java.util.List<? extends org.seasailing.protobuf.ResultDTOOrBuilder> 
         getResultsOrBuilderList() {
      if (resultsBuilder_ != null) {
        return resultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(results_);
      }
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public org.seasailing.protobuf.ResultDTO.Builder addResultsBuilder() {
      return getResultsFieldBuilder().addBuilder(
          org.seasailing.protobuf.ResultDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public org.seasailing.protobuf.ResultDTO.Builder addResultsBuilder(
        int index) {
      return getResultsFieldBuilder().addBuilder(
          index, org.seasailing.protobuf.ResultDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .org.seasailing.protobuf.ResultDTO results = 8;</code>
     */
    public java.util.List<org.seasailing.protobuf.ResultDTO.Builder> 
         getResultsBuilderList() {
      return getResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.seasailing.protobuf.ResultDTO, org.seasailing.protobuf.ResultDTO.Builder, org.seasailing.protobuf.ResultDTOOrBuilder> 
        getResultsFieldBuilder() {
      if (resultsBuilder_ == null) {
        resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.seasailing.protobuf.ResultDTO, org.seasailing.protobuf.ResultDTO.Builder, org.seasailing.protobuf.ResultDTOOrBuilder>(
                results_,
                ((bitField0_ & 0x00000080) == 0x00000080),
                getParentForChildren(),
                isClean());
        results_ = null;
      }
      return resultsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.RaceDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.RaceDTO)
  private static final org.seasailing.protobuf.RaceDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.RaceDTO();
  }

  public static org.seasailing.protobuf.RaceDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RaceDTO>
      PARSER = new com.google.protobuf.AbstractParser<RaceDTO>() {
    public RaceDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RaceDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RaceDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RaceDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.RaceDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

