// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.ResultDTO}
 */
public  final class ResultDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.ResultDTO)
    ResultDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ResultDTO.newBuilder() to construct.
  private ResultDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ResultDTO() {
    status_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ResultDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (boat_ != null) {
              subBuilder = boat_.toBuilder();
            }
            boat_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(boat_);
              boat_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (rating_ != null) {
              subBuilder = rating_.toBuilder();
            }
            rating_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(rating_);
              rating_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 34: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (finishTime_ != null) {
              subBuilder = finishTime_.toBuilder();
            }
            finishTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(finishTime_);
              finishTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (elapsedTime_ != null) {
              subBuilder = elapsedTime_.toBuilder();
            }
            elapsedTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elapsedTime_);
              elapsedTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (correctedTime_ != null) {
              subBuilder = correctedTime_.toBuilder();
            }
            correctedTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(correctedTime_);
              correctedTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            org.seasailing.protobuf.RaceDTO.Builder subBuilder = null;
            if (race_ != null) {
              subBuilder = race_.toBuilder();
            }
            race_ = input.readMessage(org.seasailing.protobuf.RaceDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(race_);
              race_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ResultDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ResultDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.ResultDTO.class, org.seasailing.protobuf.ResultDTO.Builder.class);
  }

  public static final int BOAT_FIELD_NUMBER = 1;
  private com.google.protobuf.StringValue boat_;
  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  public boolean hasBoat() {
    return boat_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  public com.google.protobuf.StringValue getBoat() {
    return boat_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : boat_;
  }
  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getBoatOrBuilder() {
    return getBoat();
  }

  public static final int RATING_FIELD_NUMBER = 2;
  private com.google.protobuf.Int32Value rating_;
  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  public boolean hasRating() {
    return rating_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  public com.google.protobuf.Int32Value getRating() {
    return rating_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
  }
  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder() {
    return getRating();
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>.org.seasailing.protobuf.Status status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.org.seasailing.protobuf.Status status = 3;</code>
   */
  public org.seasailing.protobuf.Status getStatus() {
    org.seasailing.protobuf.Status result = org.seasailing.protobuf.Status.valueOf(status_);
    return result == null ? org.seasailing.protobuf.Status.UNRECOGNIZED : result;
  }

  public static final int FINISHTIME_FIELD_NUMBER = 4;
  private com.google.protobuf.Int64Value finishTime_;
  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  public boolean hasFinishTime() {
    return finishTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  public com.google.protobuf.Int64Value getFinishTime() {
    return finishTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getFinishTimeOrBuilder() {
    return getFinishTime();
  }

  public static final int ELAPSEDTIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Int64Value elapsedTime_;
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  public boolean hasElapsedTime() {
    return elapsedTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  public com.google.protobuf.Int64Value getElapsedTime() {
    return elapsedTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : elapsedTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getElapsedTimeOrBuilder() {
    return getElapsedTime();
  }

  public static final int CORRECTEDTIME_FIELD_NUMBER = 6;
  private com.google.protobuf.Int64Value correctedTime_;
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  public boolean hasCorrectedTime() {
    return correctedTime_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  public com.google.protobuf.Int64Value getCorrectedTime() {
    return correctedTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : correctedTime_;
  }
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getCorrectedTimeOrBuilder() {
    return getCorrectedTime();
  }

  public static final int RACE_FIELD_NUMBER = 7;
  private org.seasailing.protobuf.RaceDTO race_;
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  public boolean hasRace() {
    return race_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  public org.seasailing.protobuf.RaceDTO getRace() {
    return race_ == null ? org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
  }
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  public org.seasailing.protobuf.RaceDTOOrBuilder getRaceOrBuilder() {
    return getRace();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (boat_ != null) {
      output.writeMessage(1, getBoat());
    }
    if (rating_ != null) {
      output.writeMessage(2, getRating());
    }
    if (status_ != org.seasailing.protobuf.Status.FINISHED.getNumber()) {
      output.writeEnum(3, status_);
    }
    if (finishTime_ != null) {
      output.writeMessage(4, getFinishTime());
    }
    if (elapsedTime_ != null) {
      output.writeMessage(5, getElapsedTime());
    }
    if (correctedTime_ != null) {
      output.writeMessage(6, getCorrectedTime());
    }
    if (race_ != null) {
      output.writeMessage(7, getRace());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (boat_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBoat());
    }
    if (rating_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRating());
    }
    if (status_ != org.seasailing.protobuf.Status.FINISHED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, status_);
    }
    if (finishTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFinishTime());
    }
    if (elapsedTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getElapsedTime());
    }
    if (correctedTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCorrectedTime());
    }
    if (race_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getRace());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.ResultDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.ResultDTO other = (org.seasailing.protobuf.ResultDTO) obj;

    boolean result = true;
    result = result && (hasBoat() == other.hasBoat());
    if (hasBoat()) {
      result = result && getBoat()
          .equals(other.getBoat());
    }
    result = result && (hasRating() == other.hasRating());
    if (hasRating()) {
      result = result && getRating()
          .equals(other.getRating());
    }
    result = result && status_ == other.status_;
    result = result && (hasFinishTime() == other.hasFinishTime());
    if (hasFinishTime()) {
      result = result && getFinishTime()
          .equals(other.getFinishTime());
    }
    result = result && (hasElapsedTime() == other.hasElapsedTime());
    if (hasElapsedTime()) {
      result = result && getElapsedTime()
          .equals(other.getElapsedTime());
    }
    result = result && (hasCorrectedTime() == other.hasCorrectedTime());
    if (hasCorrectedTime()) {
      result = result && getCorrectedTime()
          .equals(other.getCorrectedTime());
    }
    result = result && (hasRace() == other.hasRace());
    if (hasRace()) {
      result = result && getRace()
          .equals(other.getRace());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBoat()) {
      hash = (37 * hash) + BOAT_FIELD_NUMBER;
      hash = (53 * hash) + getBoat().hashCode();
    }
    if (hasRating()) {
      hash = (37 * hash) + RATING_FIELD_NUMBER;
      hash = (53 * hash) + getRating().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasFinishTime()) {
      hash = (37 * hash) + FINISHTIME_FIELD_NUMBER;
      hash = (53 * hash) + getFinishTime().hashCode();
    }
    if (hasElapsedTime()) {
      hash = (37 * hash) + ELAPSEDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getElapsedTime().hashCode();
    }
    if (hasCorrectedTime()) {
      hash = (37 * hash) + CORRECTEDTIME_FIELD_NUMBER;
      hash = (53 * hash) + getCorrectedTime().hashCode();
    }
    if (hasRace()) {
      hash = (37 * hash) + RACE_FIELD_NUMBER;
      hash = (53 * hash) + getRace().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.ResultDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.ResultDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ResultDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.ResultDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.ResultDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.ResultDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.ResultDTO)
      org.seasailing.protobuf.ResultDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ResultDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ResultDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.ResultDTO.class, org.seasailing.protobuf.ResultDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.ResultDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (boatBuilder_ == null) {
        boat_ = null;
      } else {
        boat_ = null;
        boatBuilder_ = null;
      }
      if (ratingBuilder_ == null) {
        rating_ = null;
      } else {
        rating_ = null;
        ratingBuilder_ = null;
      }
      status_ = 0;

      if (finishTimeBuilder_ == null) {
        finishTime_ = null;
      } else {
        finishTime_ = null;
        finishTimeBuilder_ = null;
      }
      if (elapsedTimeBuilder_ == null) {
        elapsedTime_ = null;
      } else {
        elapsedTime_ = null;
        elapsedTimeBuilder_ = null;
      }
      if (correctedTimeBuilder_ == null) {
        correctedTime_ = null;
      } else {
        correctedTime_ = null;
        correctedTimeBuilder_ = null;
      }
      if (raceBuilder_ == null) {
        race_ = null;
      } else {
        race_ = null;
        raceBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_ResultDTO_descriptor;
    }

    public org.seasailing.protobuf.ResultDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.ResultDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.ResultDTO build() {
      org.seasailing.protobuf.ResultDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.ResultDTO buildPartial() {
      org.seasailing.protobuf.ResultDTO result = new org.seasailing.protobuf.ResultDTO(this);
      if (boatBuilder_ == null) {
        result.boat_ = boat_;
      } else {
        result.boat_ = boatBuilder_.build();
      }
      if (ratingBuilder_ == null) {
        result.rating_ = rating_;
      } else {
        result.rating_ = ratingBuilder_.build();
      }
      result.status_ = status_;
      if (finishTimeBuilder_ == null) {
        result.finishTime_ = finishTime_;
      } else {
        result.finishTime_ = finishTimeBuilder_.build();
      }
      if (elapsedTimeBuilder_ == null) {
        result.elapsedTime_ = elapsedTime_;
      } else {
        result.elapsedTime_ = elapsedTimeBuilder_.build();
      }
      if (correctedTimeBuilder_ == null) {
        result.correctedTime_ = correctedTime_;
      } else {
        result.correctedTime_ = correctedTimeBuilder_.build();
      }
      if (raceBuilder_ == null) {
        result.race_ = race_;
      } else {
        result.race_ = raceBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.ResultDTO) {
        return mergeFrom((org.seasailing.protobuf.ResultDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.ResultDTO other) {
      if (other == org.seasailing.protobuf.ResultDTO.getDefaultInstance()) return this;
      if (other.hasBoat()) {
        mergeBoat(other.getBoat());
      }
      if (other.hasRating()) {
        mergeRating(other.getRating());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasFinishTime()) {
        mergeFinishTime(other.getFinishTime());
      }
      if (other.hasElapsedTime()) {
        mergeElapsedTime(other.getElapsedTime());
      }
      if (other.hasCorrectedTime()) {
        mergeCorrectedTime(other.getCorrectedTime());
      }
      if (other.hasRace()) {
        mergeRace(other.getRace());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.ResultDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.ResultDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.StringValue boat_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> boatBuilder_;
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public boolean hasBoat() {
      return boatBuilder_ != null || boat_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public com.google.protobuf.StringValue getBoat() {
      if (boatBuilder_ == null) {
        return boat_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : boat_;
      } else {
        return boatBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public Builder setBoat(com.google.protobuf.StringValue value) {
      if (boatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        boat_ = value;
        onChanged();
      } else {
        boatBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public Builder setBoat(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (boatBuilder_ == null) {
        boat_ = builderForValue.build();
        onChanged();
      } else {
        boatBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public Builder mergeBoat(com.google.protobuf.StringValue value) {
      if (boatBuilder_ == null) {
        if (boat_ != null) {
          boat_ =
            com.google.protobuf.StringValue.newBuilder(boat_).mergeFrom(value).buildPartial();
        } else {
          boat_ = value;
        }
        onChanged();
      } else {
        boatBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public Builder clearBoat() {
      if (boatBuilder_ == null) {
        boat_ = null;
        onChanged();
      } else {
        boat_ = null;
        boatBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public com.google.protobuf.StringValue.Builder getBoatBuilder() {
      
      onChanged();
      return getBoatFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getBoatOrBuilder() {
      if (boatBuilder_ != null) {
        return boatBuilder_.getMessageOrBuilder();
      } else {
        return boat_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : boat_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue boat = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getBoatFieldBuilder() {
      if (boatBuilder_ == null) {
        boatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getBoat(),
                getParentForChildren(),
                isClean());
        boat_ = null;
      }
      return boatBuilder_;
    }

    private com.google.protobuf.Int32Value rating_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> ratingBuilder_;
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public boolean hasRating() {
      return ratingBuilder_ != null || rating_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public com.google.protobuf.Int32Value getRating() {
      if (ratingBuilder_ == null) {
        return rating_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
      } else {
        return ratingBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public Builder setRating(com.google.protobuf.Int32Value value) {
      if (ratingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rating_ = value;
        onChanged();
      } else {
        ratingBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public Builder setRating(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (ratingBuilder_ == null) {
        rating_ = builderForValue.build();
        onChanged();
      } else {
        ratingBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public Builder mergeRating(com.google.protobuf.Int32Value value) {
      if (ratingBuilder_ == null) {
        if (rating_ != null) {
          rating_ =
            com.google.protobuf.Int32Value.newBuilder(rating_).mergeFrom(value).buildPartial();
        } else {
          rating_ = value;
        }
        onChanged();
      } else {
        ratingBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public Builder clearRating() {
      if (ratingBuilder_ == null) {
        rating_ = null;
        onChanged();
      } else {
        rating_ = null;
        ratingBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public com.google.protobuf.Int32Value.Builder getRatingBuilder() {
      
      onChanged();
      return getRatingFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder() {
      if (ratingBuilder_ != null) {
        return ratingBuilder_.getMessageOrBuilder();
      } else {
        return rating_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : rating_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value rating = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getRatingFieldBuilder() {
      if (ratingBuilder_ == null) {
        ratingBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getRating(),
                getParentForChildren(),
                isClean());
        rating_ = null;
      }
      return ratingBuilder_;
    }

    private int status_ = 0;
    /**
     * <code>.org.seasailing.protobuf.Status status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 3;</code>
     */
    public org.seasailing.protobuf.Status getStatus() {
      org.seasailing.protobuf.Status result = org.seasailing.protobuf.Status.valueOf(status_);
      return result == null ? org.seasailing.protobuf.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 3;</code>
     */
    public Builder setStatus(org.seasailing.protobuf.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.Status status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value finishTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> finishTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public boolean hasFinishTime() {
      return finishTimeBuilder_ != null || finishTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public com.google.protobuf.Int64Value getFinishTime() {
      if (finishTimeBuilder_ == null) {
        return finishTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
      } else {
        return finishTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public Builder setFinishTime(com.google.protobuf.Int64Value value) {
      if (finishTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        finishTime_ = value;
        onChanged();
      } else {
        finishTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public Builder setFinishTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (finishTimeBuilder_ == null) {
        finishTime_ = builderForValue.build();
        onChanged();
      } else {
        finishTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public Builder mergeFinishTime(com.google.protobuf.Int64Value value) {
      if (finishTimeBuilder_ == null) {
        if (finishTime_ != null) {
          finishTime_ =
            com.google.protobuf.Int64Value.newBuilder(finishTime_).mergeFrom(value).buildPartial();
        } else {
          finishTime_ = value;
        }
        onChanged();
      } else {
        finishTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public Builder clearFinishTime() {
      if (finishTimeBuilder_ == null) {
        finishTime_ = null;
        onChanged();
      } else {
        finishTime_ = null;
        finishTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public com.google.protobuf.Int64Value.Builder getFinishTimeBuilder() {
      
      onChanged();
      return getFinishTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getFinishTimeOrBuilder() {
      if (finishTimeBuilder_ != null) {
        return finishTimeBuilder_.getMessageOrBuilder();
      } else {
        return finishTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : finishTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value finishTime = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getFinishTimeFieldBuilder() {
      if (finishTimeBuilder_ == null) {
        finishTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getFinishTime(),
                getParentForChildren(),
                isClean());
        finishTime_ = null;
      }
      return finishTimeBuilder_;
    }

    private com.google.protobuf.Int64Value elapsedTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> elapsedTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public boolean hasElapsedTime() {
      return elapsedTimeBuilder_ != null || elapsedTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public com.google.protobuf.Int64Value getElapsedTime() {
      if (elapsedTimeBuilder_ == null) {
        return elapsedTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : elapsedTime_;
      } else {
        return elapsedTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public Builder setElapsedTime(com.google.protobuf.Int64Value value) {
      if (elapsedTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elapsedTime_ = value;
        onChanged();
      } else {
        elapsedTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public Builder setElapsedTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (elapsedTimeBuilder_ == null) {
        elapsedTime_ = builderForValue.build();
        onChanged();
      } else {
        elapsedTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public Builder mergeElapsedTime(com.google.protobuf.Int64Value value) {
      if (elapsedTimeBuilder_ == null) {
        if (elapsedTime_ != null) {
          elapsedTime_ =
            com.google.protobuf.Int64Value.newBuilder(elapsedTime_).mergeFrom(value).buildPartial();
        } else {
          elapsedTime_ = value;
        }
        onChanged();
      } else {
        elapsedTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public Builder clearElapsedTime() {
      if (elapsedTimeBuilder_ == null) {
        elapsedTime_ = null;
        onChanged();
      } else {
        elapsedTime_ = null;
        elapsedTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public com.google.protobuf.Int64Value.Builder getElapsedTimeBuilder() {
      
      onChanged();
      return getElapsedTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getElapsedTimeOrBuilder() {
      if (elapsedTimeBuilder_ != null) {
        return elapsedTimeBuilder_.getMessageOrBuilder();
      } else {
        return elapsedTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : elapsedTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getElapsedTimeFieldBuilder() {
      if (elapsedTimeBuilder_ == null) {
        elapsedTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getElapsedTime(),
                getParentForChildren(),
                isClean());
        elapsedTime_ = null;
      }
      return elapsedTimeBuilder_;
    }

    private com.google.protobuf.Int64Value correctedTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> correctedTimeBuilder_;
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public boolean hasCorrectedTime() {
      return correctedTimeBuilder_ != null || correctedTime_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public com.google.protobuf.Int64Value getCorrectedTime() {
      if (correctedTimeBuilder_ == null) {
        return correctedTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : correctedTime_;
      } else {
        return correctedTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public Builder setCorrectedTime(com.google.protobuf.Int64Value value) {
      if (correctedTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        correctedTime_ = value;
        onChanged();
      } else {
        correctedTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public Builder setCorrectedTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (correctedTimeBuilder_ == null) {
        correctedTime_ = builderForValue.build();
        onChanged();
      } else {
        correctedTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public Builder mergeCorrectedTime(com.google.protobuf.Int64Value value) {
      if (correctedTimeBuilder_ == null) {
        if (correctedTime_ != null) {
          correctedTime_ =
            com.google.protobuf.Int64Value.newBuilder(correctedTime_).mergeFrom(value).buildPartial();
        } else {
          correctedTime_ = value;
        }
        onChanged();
      } else {
        correctedTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public Builder clearCorrectedTime() {
      if (correctedTimeBuilder_ == null) {
        correctedTime_ = null;
        onChanged();
      } else {
        correctedTime_ = null;
        correctedTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public com.google.protobuf.Int64Value.Builder getCorrectedTimeBuilder() {
      
      onChanged();
      return getCorrectedTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getCorrectedTimeOrBuilder() {
      if (correctedTimeBuilder_ != null) {
        return correctedTimeBuilder_.getMessageOrBuilder();
      } else {
        return correctedTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : correctedTime_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getCorrectedTimeFieldBuilder() {
      if (correctedTimeBuilder_ == null) {
        correctedTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getCorrectedTime(),
                getParentForChildren(),
                isClean());
        correctedTime_ = null;
      }
      return correctedTimeBuilder_;
    }

    private org.seasailing.protobuf.RaceDTO race_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder> raceBuilder_;
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public boolean hasRace() {
      return raceBuilder_ != null || race_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public org.seasailing.protobuf.RaceDTO getRace() {
      if (raceBuilder_ == null) {
        return race_ == null ? org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
      } else {
        return raceBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public Builder setRace(org.seasailing.protobuf.RaceDTO value) {
      if (raceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        race_ = value;
        onChanged();
      } else {
        raceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public Builder setRace(
        org.seasailing.protobuf.RaceDTO.Builder builderForValue) {
      if (raceBuilder_ == null) {
        race_ = builderForValue.build();
        onChanged();
      } else {
        raceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public Builder mergeRace(org.seasailing.protobuf.RaceDTO value) {
      if (raceBuilder_ == null) {
        if (race_ != null) {
          race_ =
            org.seasailing.protobuf.RaceDTO.newBuilder(race_).mergeFrom(value).buildPartial();
        } else {
          race_ = value;
        }
        onChanged();
      } else {
        raceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public Builder clearRace() {
      if (raceBuilder_ == null) {
        race_ = null;
        onChanged();
      } else {
        race_ = null;
        raceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public org.seasailing.protobuf.RaceDTO.Builder getRaceBuilder() {
      
      onChanged();
      return getRaceFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    public org.seasailing.protobuf.RaceDTOOrBuilder getRaceOrBuilder() {
      if (raceBuilder_ != null) {
        return raceBuilder_.getMessageOrBuilder();
      } else {
        return race_ == null ?
            org.seasailing.protobuf.RaceDTO.getDefaultInstance() : race_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder> 
        getRaceFieldBuilder() {
      if (raceBuilder_ == null) {
        raceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.RaceDTO, org.seasailing.protobuf.RaceDTO.Builder, org.seasailing.protobuf.RaceDTOOrBuilder>(
                getRace(),
                getParentForChildren(),
                isClean());
        race_ = null;
      }
      return raceBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.ResultDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.ResultDTO)
  private static final org.seasailing.protobuf.ResultDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.ResultDTO();
  }

  public static org.seasailing.protobuf.ResultDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResultDTO>
      PARSER = new com.google.protobuf.AbstractParser<ResultDTO>() {
    public ResultDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ResultDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ResultDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResultDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.ResultDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

