// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public interface ResultDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.seasailing.protobuf.ResultDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  boolean hasBoat();
  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  com.google.protobuf.StringValue getBoat();
  /**
   * <code>.google.protobuf.StringValue boat = 1;</code>
   */
  com.google.protobuf.StringValueOrBuilder getBoatOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  boolean hasRating();
  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  com.google.protobuf.Int32Value getRating();
  /**
   * <code>.google.protobuf.Int32Value rating = 2;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getRatingOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.Status status = 3;</code>
   */
  int getStatusValue();
  /**
   * <code>.org.seasailing.protobuf.Status status = 3;</code>
   */
  org.seasailing.protobuf.Status getStatus();

  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  boolean hasFinishTime();
  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  com.google.protobuf.Int64Value getFinishTime();
  /**
   * <code>.google.protobuf.Int64Value finishTime = 4;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getFinishTimeOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  boolean hasElapsedTime();
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  com.google.protobuf.Int64Value getElapsedTime();
  /**
   * <code>.google.protobuf.Int64Value elapsedTime = 5;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getElapsedTimeOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  boolean hasCorrectedTime();
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  com.google.protobuf.Int64Value getCorrectedTime();
  /**
   * <code>.google.protobuf.Int64Value correctedTime = 6;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getCorrectedTimeOrBuilder();

  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  boolean hasRace();
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  org.seasailing.protobuf.RaceDTO getRace();
  /**
   * <code>.org.seasailing.protobuf.RaceDTO race = 7;</code>
   */
  org.seasailing.protobuf.RaceDTOOrBuilder getRaceOrBuilder();
}
