// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

public final class Seas {
  private Seas() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_PersonDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_PersonDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_ClubDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_ClubDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_BoatDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_BoatDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_HandicapDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_HandicapDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_FinishTimeDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_ResultDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_ResultDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_SeriesDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_SeriesDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_CourseDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_CourseDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_seasailing_protobuf_RaceDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_seasailing_protobuf_RaceDTO_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nSeas.proto\022\027org.seasailing.protobuf\032\036g" +
      "oogle/protobuf/wrappers.proto\"\214\001\n\003Msg\0227\n" +
      "\010severity\030\001 \001(\0162%.org.seasailing.protobu" +
      "f.Msg.Severity\022\017\n\007message\030\002 \001(\t\";\n\010Sever" +
      "ity\022\010\n\004INFO\020\000\022\013\n\007WARNING\020\001\022\t\n\005ERROR\020\002\022\r\n" +
      "\tEXCEPTION\020\003\"\221\001\n\tPersonDTO\022*\n\004name\030\001 \001(\013" +
      "2\034.google.protobuf.StringValue\022+\n\005email\030" +
      "\002 \001(\0132\034.google.protobuf.StringValue\022+\n\005p" +
      "hone\030\003 \001(\0132\034.google.protobuf.StringValue" +
      "\"\203\002\n\007ClubDTO\022\'\n\002id\030\001 \001(\0132\033.google.protob" +
      "uf.Int32Value\022*\n\004name\030\002 \001(\0132\034.google.pro" +
      "tobuf.StringValue\022+\n\005email\030\003 \001(\0132\034.googl" +
      "e.protobuf.StringValue\0227\n\013handicapper\030\004 " +
      "\001(\0132\".org.seasailing.protobuf.PersonDTO\022" +
      "=\n\017defaultHandicap\030\005 \001(\0132$.org.seasailin" +
      "g.protobuf.HandicapDTO\"\301\003\n\007BoatDTO\022:\n\004na" +
      "me\030\001 \001(\0132,.org.seasailing.protobuf.BoatD" +
      "TO.BoatNameDTO\022*\n\004make\030\002 \001(\0132\034.google.pr" +
      "otobuf.StringValue\022,\n\006length\030\003 \001(\0132\034.goo" +
      "gle.protobuf.DoubleValue\022+\n\006rating\030\004 \001(\013" +
      "2\033.google.protobuf.Int32Value\0223\n\007skipper" +
      "\030\005 \001(\0132\".org.seasailing.protobuf.PersonD" +
      "TO\022*\n\006active\030\006 \001(\0132\032.google.protobuf.Boo" +
      "lValue\022.\n\004club\030\007 \001(\0132 .org.seasailing.pr" +
      "otobuf.ClubDTO\032b\n\013BoatNameDTO\022\'\n\002id\030\001 \001(" +
      "\0132\033.google.protobuf.Int32Value\022*\n\004name\030\002" +
      " \001(\0132\034.google.protobuf.StringValue\"\256\001\n\013H" +
      "andicapDTO\0220\n\013denominator\030\001 \001(\0132\033.google" +
      ".protobuf.Int32Value\022;\n\006method\030\004 \001(\0162+.o" +
      "rg.seasailing.protobuf.HandicapDTO.Metho" +
      "d\"0\n\006Method\022\020\n\014TIME_ON_TIME\020\000\022\024\n\020TIME_ON" +
      "_DISTANCE\020\001\"\321\001\n\rFinishTimeDTO\022.\n\004boat\030\001 " +
      "\001(\0132 .org.seasailing.protobuf.BoatDTO\022/\n" +
      "\006status\030\002 \001(\0162\037.org.seasailing.protobuf." +
      "Status\022/\n\nfinishTime\030\003 \001(\0132\033.google.prot" +
      "obuf.Int64Value\022.\n\004race\030\004 \001(\0132 .org.seas" +
      "ailing.protobuf.RaceDTO\"\334\002\n\tResultDTO\022*\n" +
      "\004boat\030\001 \001(\0132\034.google.protobuf.StringValu" +
      "e\022+\n\006rating\030\002 \001(\0132\033.google.protobuf.Int3" +
      "2Value\022/\n\006status\030\003 \001(\0162\037.org.seasailing." +
      "protobuf.Status\022/\n\nfinishTime\030\004 \001(\0132\033.go" +
      "ogle.protobuf.Int64Value\0220\n\013elapsedTime\030" +
      "\005 \001(\0132\033.google.protobuf.Int64Value\0222\n\rco" +
      "rrectedTime\030\006 \001(\0132\033.google.protobuf.Int6" +
      "4Value\022.\n\004race\030\007 \001(\0132 .org.seasailing.pr" +
      "otobuf.RaceDTO\"\252\002\n\tSeriesDTO\022\'\n\002id\030\001 \001(\013" +
      "2\033.google.protobuf.Int32Value\022*\n\004name\030\002 " +
      "\001(\0132\034.google.protobuf.StringValue\0221\n\013des" +
      "cription\030\003 \001(\0132\034.google.protobuf.StringV" +
      "alue\022-\n\007sponsor\030\004 \001(\0132\034.google.protobuf." +
      "StringValue\0226\n\021defaultMultiplier\030\005 \001(\0132\033" +
      ".google.protobuf.Int32Value\022.\n\004club\030\006 \001(" +
      "\0132 .org.seasailing.protobuf.ClubDTO\"\363\001\n\t" +
      "CourseDTO\022\'\n\002id\030\001 \001(\0132\033.google.protobuf." +
      "Int32Value\022*\n\004name\030\002 \001(\0132\034.google.protob" +
      "uf.StringValue\0221\n\013description\030\003 \001(\0132\034.go" +
      "ogle.protobuf.StringValue\022.\n\010distance\030\004 " +
      "\001(\0132\034.google.protobuf.DoubleValue\022.\n\004clu" +
      "b\030\005 \001(\0132 .org.seasailing.protobuf.ClubDT" +
      "O\"\320\003\n\007RaceDTO\022\'\n\002id\030\001 \001(\0132\033.google.proto" +
      "buf.Int32Value\022.\n\tstartTime\030\002 \001(\0132\033.goog" +
      "le.protobuf.Int64Value\0222\n\006series\030\003 \001(\0132\"" +
      ".org.seasailing.protobuf.SeriesDTO\0222\n\006co" +
      "urse\030\004 \001(\0132\".org.seasailing.protobuf.Cou" +
      "rseDTO\022/\n\nmultiplier\030\005 \001(\0132\033.google.prot" +
      "obuf.Int32Value\0227\n\006option\030\006 \001(\0162\'.org.se" +
      "asailing.protobuf.RaceDTO.Option\0226\n\010hand" +
      "icap\030\007 \001(\0132$.org.seasailing.protobuf.Han" +
      "dicapDTO\0223\n\007results\030\010 \003(\0132\".org.seasaili" +
      "ng.protobuf.ResultDTO\"-\n\006Option\022\013\n\007DEFAU" +
      "LT\020\000\022\t\n\005TWICE\020\001\022\013\n\007REVERSE\020\002*1\n\006Status\022\014" +
      "\n\010FINISHED\020\000\022\007\n\003DNS\020\001\022\007\n\003DNF\020\002\022\007\n\003DSQ\020\003B" +
      "\033\n\027org.seasailing.protobufP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    internal_static_org_seasailing_protobuf_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_seasailing_protobuf_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_Msg_descriptor,
        new java.lang.String[] { "Severity", "Message", });
    internal_static_org_seasailing_protobuf_PersonDTO_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_seasailing_protobuf_PersonDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_PersonDTO_descriptor,
        new java.lang.String[] { "Name", "Email", "Phone", });
    internal_static_org_seasailing_protobuf_ClubDTO_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_seasailing_protobuf_ClubDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_ClubDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "Handicapper", "DefaultHandicap", });
    internal_static_org_seasailing_protobuf_BoatDTO_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_seasailing_protobuf_BoatDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_BoatDTO_descriptor,
        new java.lang.String[] { "Name", "Make", "Length", "Rating", "Skipper", "Active", "Club", });
    internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor =
      internal_static_org_seasailing_protobuf_BoatDTO_descriptor.getNestedTypes().get(0);
    internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_BoatDTO_BoatNameDTO_descriptor,
        new java.lang.String[] { "Id", "Name", });
    internal_static_org_seasailing_protobuf_HandicapDTO_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_seasailing_protobuf_HandicapDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_HandicapDTO_descriptor,
        new java.lang.String[] { "Denominator", "Method", });
    internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_seasailing_protobuf_FinishTimeDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_FinishTimeDTO_descriptor,
        new java.lang.String[] { "Boat", "Status", "FinishTime", "Race", });
    internal_static_org_seasailing_protobuf_ResultDTO_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_seasailing_protobuf_ResultDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_ResultDTO_descriptor,
        new java.lang.String[] { "Boat", "Rating", "Status", "FinishTime", "ElapsedTime", "CorrectedTime", "Race", });
    internal_static_org_seasailing_protobuf_SeriesDTO_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_seasailing_protobuf_SeriesDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_SeriesDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Sponsor", "DefaultMultiplier", "Club", });
    internal_static_org_seasailing_protobuf_CourseDTO_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_seasailing_protobuf_CourseDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_CourseDTO_descriptor,
        new java.lang.String[] { "Id", "Name", "Description", "Distance", "Club", });
    internal_static_org_seasailing_protobuf_RaceDTO_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_seasailing_protobuf_RaceDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_seasailing_protobuf_RaceDTO_descriptor,
        new java.lang.String[] { "Id", "StartTime", "Series", "Course", "Multiplier", "Option", "Handicap", "Results", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
