// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seas.proto

package org.seasailing.protobuf;

/**
 * Protobuf type {@code org.seasailing.protobuf.SeriesDTO}
 */
public  final class SeriesDTO extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.seasailing.protobuf.SeriesDTO)
    SeriesDTOOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SeriesDTO.newBuilder() to construct.
  private SeriesDTO(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SeriesDTO() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SeriesDTO(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (id_ != null) {
              subBuilder = id_.toBuilder();
            }
            id_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(id_);
              id_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (name_ != null) {
              subBuilder = name_.toBuilder();
            }
            name_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(name_);
              name_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (description_ != null) {
              subBuilder = description_.toBuilder();
            }
            description_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(description_);
              description_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.StringValue.Builder subBuilder = null;
            if (sponsor_ != null) {
              subBuilder = sponsor_.toBuilder();
            }
            sponsor_ = input.readMessage(com.google.protobuf.StringValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sponsor_);
              sponsor_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (defaultMultiplier_ != null) {
              subBuilder = defaultMultiplier_.toBuilder();
            }
            defaultMultiplier_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(defaultMultiplier_);
              defaultMultiplier_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            org.seasailing.protobuf.ClubDTO.Builder subBuilder = null;
            if (club_ != null) {
              subBuilder = club_.toBuilder();
            }
            club_ = input.readMessage(org.seasailing.protobuf.ClubDTO.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(club_);
              club_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_SeriesDTO_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_SeriesDTO_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.seasailing.protobuf.SeriesDTO.class, org.seasailing.protobuf.SeriesDTO.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value id_;
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public boolean hasId() {
    return id_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32Value getId() {
    return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
  }
  /**
   * <code>.google.protobuf.Int32Value id = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
    return getId();
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private com.google.protobuf.StringValue name_;
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public boolean hasName() {
    return name_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public com.google.protobuf.StringValue getName() {
    return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
  }
  /**
   * <code>.google.protobuf.StringValue name = 2;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
    return getName();
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private com.google.protobuf.StringValue description_;
  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  public boolean hasDescription() {
    return description_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  public com.google.protobuf.StringValue getDescription() {
    return description_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : description_;
  }
  /**
   * <code>.google.protobuf.StringValue description = 3;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder() {
    return getDescription();
  }

  public static final int SPONSOR_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue sponsor_;
  /**
   * <code>.google.protobuf.StringValue sponsor = 4;</code>
   */
  public boolean hasSponsor() {
    return sponsor_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue sponsor = 4;</code>
   */
  public com.google.protobuf.StringValue getSponsor() {
    return sponsor_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sponsor_;
  }
  /**
   * <code>.google.protobuf.StringValue sponsor = 4;</code>
   */
  public com.google.protobuf.StringValueOrBuilder getSponsorOrBuilder() {
    return getSponsor();
  }

  public static final int DEFAULTMULTIPLIER_FIELD_NUMBER = 5;
  private com.google.protobuf.Int32Value defaultMultiplier_;
  /**
   * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
   */
  public boolean hasDefaultMultiplier() {
    return defaultMultiplier_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
   */
  public com.google.protobuf.Int32Value getDefaultMultiplier() {
    return defaultMultiplier_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : defaultMultiplier_;
  }
  /**
   * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getDefaultMultiplierOrBuilder() {
    return getDefaultMultiplier();
  }

  public static final int CLUB_FIELD_NUMBER = 6;
  private org.seasailing.protobuf.ClubDTO club_;
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
   */
  public boolean hasClub() {
    return club_ != null;
  }
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
   */
  public org.seasailing.protobuf.ClubDTO getClub() {
    return club_ == null ? org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
  }
  /**
   * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
   */
  public org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder() {
    return getClub();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != null) {
      output.writeMessage(1, getId());
    }
    if (name_ != null) {
      output.writeMessage(2, getName());
    }
    if (description_ != null) {
      output.writeMessage(3, getDescription());
    }
    if (sponsor_ != null) {
      output.writeMessage(4, getSponsor());
    }
    if (defaultMultiplier_ != null) {
      output.writeMessage(5, getDefaultMultiplier());
    }
    if (club_ != null) {
      output.writeMessage(6, getClub());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getId());
    }
    if (name_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getName());
    }
    if (description_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDescription());
    }
    if (sponsor_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSponsor());
    }
    if (defaultMultiplier_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDefaultMultiplier());
    }
    if (club_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getClub());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.seasailing.protobuf.SeriesDTO)) {
      return super.equals(obj);
    }
    org.seasailing.protobuf.SeriesDTO other = (org.seasailing.protobuf.SeriesDTO) obj;

    boolean result = true;
    result = result && (hasId() == other.hasId());
    if (hasId()) {
      result = result && getId()
          .equals(other.getId());
    }
    result = result && (hasName() == other.hasName());
    if (hasName()) {
      result = result && getName()
          .equals(other.getName());
    }
    result = result && (hasDescription() == other.hasDescription());
    if (hasDescription()) {
      result = result && getDescription()
          .equals(other.getDescription());
    }
    result = result && (hasSponsor() == other.hasSponsor());
    if (hasSponsor()) {
      result = result && getSponsor()
          .equals(other.getSponsor());
    }
    result = result && (hasDefaultMultiplier() == other.hasDefaultMultiplier());
    if (hasDefaultMultiplier()) {
      result = result && getDefaultMultiplier()
          .equals(other.getDefaultMultiplier());
    }
    result = result && (hasClub() == other.hasClub());
    if (hasClub()) {
      result = result && getClub()
          .equals(other.getClub());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasDescription()) {
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
    }
    if (hasSponsor()) {
      hash = (37 * hash) + SPONSOR_FIELD_NUMBER;
      hash = (53 * hash) + getSponsor().hashCode();
    }
    if (hasDefaultMultiplier()) {
      hash = (37 * hash) + DEFAULTMULTIPLIER_FIELD_NUMBER;
      hash = (53 * hash) + getDefaultMultiplier().hashCode();
    }
    if (hasClub()) {
      hash = (37 * hash) + CLUB_FIELD_NUMBER;
      hash = (53 * hash) + getClub().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.SeriesDTO parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.SeriesDTO parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.seasailing.protobuf.SeriesDTO parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.seasailing.protobuf.SeriesDTO prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.seasailing.protobuf.SeriesDTO}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.seasailing.protobuf.SeriesDTO)
      org.seasailing.protobuf.SeriesDTOOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_SeriesDTO_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_SeriesDTO_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.seasailing.protobuf.SeriesDTO.class, org.seasailing.protobuf.SeriesDTO.Builder.class);
    }

    // Construct using org.seasailing.protobuf.SeriesDTO.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (idBuilder_ == null) {
        id_ = null;
      } else {
        id_ = null;
        idBuilder_ = null;
      }
      if (nameBuilder_ == null) {
        name_ = null;
      } else {
        name_ = null;
        nameBuilder_ = null;
      }
      if (descriptionBuilder_ == null) {
        description_ = null;
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }
      if (sponsorBuilder_ == null) {
        sponsor_ = null;
      } else {
        sponsor_ = null;
        sponsorBuilder_ = null;
      }
      if (defaultMultiplierBuilder_ == null) {
        defaultMultiplier_ = null;
      } else {
        defaultMultiplier_ = null;
        defaultMultiplierBuilder_ = null;
      }
      if (clubBuilder_ == null) {
        club_ = null;
      } else {
        club_ = null;
        clubBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.seasailing.protobuf.Seas.internal_static_org_seasailing_protobuf_SeriesDTO_descriptor;
    }

    public org.seasailing.protobuf.SeriesDTO getDefaultInstanceForType() {
      return org.seasailing.protobuf.SeriesDTO.getDefaultInstance();
    }

    public org.seasailing.protobuf.SeriesDTO build() {
      org.seasailing.protobuf.SeriesDTO result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.seasailing.protobuf.SeriesDTO buildPartial() {
      org.seasailing.protobuf.SeriesDTO result = new org.seasailing.protobuf.SeriesDTO(this);
      if (idBuilder_ == null) {
        result.id_ = id_;
      } else {
        result.id_ = idBuilder_.build();
      }
      if (nameBuilder_ == null) {
        result.name_ = name_;
      } else {
        result.name_ = nameBuilder_.build();
      }
      if (descriptionBuilder_ == null) {
        result.description_ = description_;
      } else {
        result.description_ = descriptionBuilder_.build();
      }
      if (sponsorBuilder_ == null) {
        result.sponsor_ = sponsor_;
      } else {
        result.sponsor_ = sponsorBuilder_.build();
      }
      if (defaultMultiplierBuilder_ == null) {
        result.defaultMultiplier_ = defaultMultiplier_;
      } else {
        result.defaultMultiplier_ = defaultMultiplierBuilder_.build();
      }
      if (clubBuilder_ == null) {
        result.club_ = club_;
      } else {
        result.club_ = clubBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.seasailing.protobuf.SeriesDTO) {
        return mergeFrom((org.seasailing.protobuf.SeriesDTO)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.seasailing.protobuf.SeriesDTO other) {
      if (other == org.seasailing.protobuf.SeriesDTO.getDefaultInstance()) return this;
      if (other.hasId()) {
        mergeId(other.getId());
      }
      if (other.hasName()) {
        mergeName(other.getName());
      }
      if (other.hasDescription()) {
        mergeDescription(other.getDescription());
      }
      if (other.hasSponsor()) {
        mergeSponsor(other.getSponsor());
      }
      if (other.hasDefaultMultiplier()) {
        mergeDefaultMultiplier(other.getDefaultMultiplier());
      }
      if (other.hasClub()) {
        mergeClub(other.getClub());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.seasailing.protobuf.SeriesDTO parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.seasailing.protobuf.SeriesDTO) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int32Value id_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> idBuilder_;
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public boolean hasId() {
      return idBuilder_ != null || id_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value getId() {
      if (idBuilder_ == null) {
        return id_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      } else {
        return idBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        id_ = value;
        onChanged();
      } else {
        idBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder setId(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (idBuilder_ == null) {
        id_ = builderForValue.build();
        onChanged();
      } else {
        idBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder mergeId(com.google.protobuf.Int32Value value) {
      if (idBuilder_ == null) {
        if (id_ != null) {
          id_ =
            com.google.protobuf.Int32Value.newBuilder(id_).mergeFrom(value).buildPartial();
        } else {
          id_ = value;
        }
        onChanged();
      } else {
        idBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public Builder clearId() {
      if (idBuilder_ == null) {
        id_ = null;
        onChanged();
      } else {
        id_ = null;
        idBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getIdBuilder() {
      
      onChanged();
      return getIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getIdOrBuilder() {
      if (idBuilder_ != null) {
        return idBuilder_.getMessageOrBuilder();
      } else {
        return id_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : id_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value id = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getIdFieldBuilder() {
      if (idBuilder_ == null) {
        idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getId(),
                getParentForChildren(),
                isClean());
        id_ = null;
      }
      return idBuilder_;
    }

    private com.google.protobuf.StringValue name_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> nameBuilder_;
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public boolean hasName() {
      return nameBuilder_ != null || name_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue getName() {
      if (nameBuilder_ == null) {
        return name_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : name_;
      } else {
        return nameBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        name_ = value;
        onChanged();
      } else {
        nameBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder setName(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (nameBuilder_ == null) {
        name_ = builderForValue.build();
        onChanged();
      } else {
        nameBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder mergeName(com.google.protobuf.StringValue value) {
      if (nameBuilder_ == null) {
        if (name_ != null) {
          name_ =
            com.google.protobuf.StringValue.newBuilder(name_).mergeFrom(value).buildPartial();
        } else {
          name_ = value;
        }
        onChanged();
      } else {
        nameBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public Builder clearName() {
      if (nameBuilder_ == null) {
        name_ = null;
        onChanged();
      } else {
        name_ = null;
        nameBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValue.Builder getNameBuilder() {
      
      onChanged();
      return getNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getNameOrBuilder() {
      if (nameBuilder_ != null) {
        return nameBuilder_.getMessageOrBuilder();
      } else {
        return name_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : name_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue name = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getNameFieldBuilder() {
      if (nameBuilder_ == null) {
        nameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getName(),
                getParentForChildren(),
                isClean());
        name_ = null;
      }
      return nameBuilder_;
    }

    private com.google.protobuf.StringValue description_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> descriptionBuilder_;
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public boolean hasDescription() {
      return descriptionBuilder_ != null || description_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public com.google.protobuf.StringValue getDescription() {
      if (descriptionBuilder_ == null) {
        return description_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : description_;
      } else {
        return descriptionBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public Builder setDescription(com.google.protobuf.StringValue value) {
      if (descriptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        description_ = value;
        onChanged();
      } else {
        descriptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public Builder setDescription(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (descriptionBuilder_ == null) {
        description_ = builderForValue.build();
        onChanged();
      } else {
        descriptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public Builder mergeDescription(com.google.protobuf.StringValue value) {
      if (descriptionBuilder_ == null) {
        if (description_ != null) {
          description_ =
            com.google.protobuf.StringValue.newBuilder(description_).mergeFrom(value).buildPartial();
        } else {
          description_ = value;
        }
        onChanged();
      } else {
        descriptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public Builder clearDescription() {
      if (descriptionBuilder_ == null) {
        description_ = null;
        onChanged();
      } else {
        description_ = null;
        descriptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public com.google.protobuf.StringValue.Builder getDescriptionBuilder() {
      
      onChanged();
      return getDescriptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDescriptionOrBuilder() {
      if (descriptionBuilder_ != null) {
        return descriptionBuilder_.getMessageOrBuilder();
      } else {
        return description_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : description_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue description = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getDescriptionFieldBuilder() {
      if (descriptionBuilder_ == null) {
        descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getDescription(),
                getParentForChildren(),
                isClean());
        description_ = null;
      }
      return descriptionBuilder_;
    }

    private com.google.protobuf.StringValue sponsor_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> sponsorBuilder_;
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public boolean hasSponsor() {
      return sponsorBuilder_ != null || sponsor_ != null;
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public com.google.protobuf.StringValue getSponsor() {
      if (sponsorBuilder_ == null) {
        return sponsor_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : sponsor_;
      } else {
        return sponsorBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public Builder setSponsor(com.google.protobuf.StringValue value) {
      if (sponsorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sponsor_ = value;
        onChanged();
      } else {
        sponsorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public Builder setSponsor(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (sponsorBuilder_ == null) {
        sponsor_ = builderForValue.build();
        onChanged();
      } else {
        sponsorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public Builder mergeSponsor(com.google.protobuf.StringValue value) {
      if (sponsorBuilder_ == null) {
        if (sponsor_ != null) {
          sponsor_ =
            com.google.protobuf.StringValue.newBuilder(sponsor_).mergeFrom(value).buildPartial();
        } else {
          sponsor_ = value;
        }
        onChanged();
      } else {
        sponsorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public Builder clearSponsor() {
      if (sponsorBuilder_ == null) {
        sponsor_ = null;
        onChanged();
      } else {
        sponsor_ = null;
        sponsorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public com.google.protobuf.StringValue.Builder getSponsorBuilder() {
      
      onChanged();
      return getSponsorFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    public com.google.protobuf.StringValueOrBuilder getSponsorOrBuilder() {
      if (sponsorBuilder_ != null) {
        return sponsorBuilder_.getMessageOrBuilder();
      } else {
        return sponsor_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : sponsor_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue sponsor = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getSponsorFieldBuilder() {
      if (sponsorBuilder_ == null) {
        sponsorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getSponsor(),
                getParentForChildren(),
                isClean());
        sponsor_ = null;
      }
      return sponsorBuilder_;
    }

    private com.google.protobuf.Int32Value defaultMultiplier_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> defaultMultiplierBuilder_;
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public boolean hasDefaultMultiplier() {
      return defaultMultiplierBuilder_ != null || defaultMultiplier_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public com.google.protobuf.Int32Value getDefaultMultiplier() {
      if (defaultMultiplierBuilder_ == null) {
        return defaultMultiplier_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : defaultMultiplier_;
      } else {
        return defaultMultiplierBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public Builder setDefaultMultiplier(com.google.protobuf.Int32Value value) {
      if (defaultMultiplierBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        defaultMultiplier_ = value;
        onChanged();
      } else {
        defaultMultiplierBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public Builder setDefaultMultiplier(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (defaultMultiplierBuilder_ == null) {
        defaultMultiplier_ = builderForValue.build();
        onChanged();
      } else {
        defaultMultiplierBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public Builder mergeDefaultMultiplier(com.google.protobuf.Int32Value value) {
      if (defaultMultiplierBuilder_ == null) {
        if (defaultMultiplier_ != null) {
          defaultMultiplier_ =
            com.google.protobuf.Int32Value.newBuilder(defaultMultiplier_).mergeFrom(value).buildPartial();
        } else {
          defaultMultiplier_ = value;
        }
        onChanged();
      } else {
        defaultMultiplierBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public Builder clearDefaultMultiplier() {
      if (defaultMultiplierBuilder_ == null) {
        defaultMultiplier_ = null;
        onChanged();
      } else {
        defaultMultiplier_ = null;
        defaultMultiplierBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public com.google.protobuf.Int32Value.Builder getDefaultMultiplierBuilder() {
      
      onChanged();
      return getDefaultMultiplierFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getDefaultMultiplierOrBuilder() {
      if (defaultMultiplierBuilder_ != null) {
        return defaultMultiplierBuilder_.getMessageOrBuilder();
      } else {
        return defaultMultiplier_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : defaultMultiplier_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value defaultMultiplier = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getDefaultMultiplierFieldBuilder() {
      if (defaultMultiplierBuilder_ == null) {
        defaultMultiplierBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getDefaultMultiplier(),
                getParentForChildren(),
                isClean());
        defaultMultiplier_ = null;
      }
      return defaultMultiplierBuilder_;
    }

    private org.seasailing.protobuf.ClubDTO club_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder> clubBuilder_;
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public boolean hasClub() {
      return clubBuilder_ != null || club_ != null;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public org.seasailing.protobuf.ClubDTO getClub() {
      if (clubBuilder_ == null) {
        return club_ == null ? org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
      } else {
        return clubBuilder_.getMessage();
      }
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public Builder setClub(org.seasailing.protobuf.ClubDTO value) {
      if (clubBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        club_ = value;
        onChanged();
      } else {
        clubBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public Builder setClub(
        org.seasailing.protobuf.ClubDTO.Builder builderForValue) {
      if (clubBuilder_ == null) {
        club_ = builderForValue.build();
        onChanged();
      } else {
        clubBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public Builder mergeClub(org.seasailing.protobuf.ClubDTO value) {
      if (clubBuilder_ == null) {
        if (club_ != null) {
          club_ =
            org.seasailing.protobuf.ClubDTO.newBuilder(club_).mergeFrom(value).buildPartial();
        } else {
          club_ = value;
        }
        onChanged();
      } else {
        clubBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public Builder clearClub() {
      if (clubBuilder_ == null) {
        club_ = null;
        onChanged();
      } else {
        club_ = null;
        clubBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public org.seasailing.protobuf.ClubDTO.Builder getClubBuilder() {
      
      onChanged();
      return getClubFieldBuilder().getBuilder();
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    public org.seasailing.protobuf.ClubDTOOrBuilder getClubOrBuilder() {
      if (clubBuilder_ != null) {
        return clubBuilder_.getMessageOrBuilder();
      } else {
        return club_ == null ?
            org.seasailing.protobuf.ClubDTO.getDefaultInstance() : club_;
      }
    }
    /**
     * <code>.org.seasailing.protobuf.ClubDTO club = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder> 
        getClubFieldBuilder() {
      if (clubBuilder_ == null) {
        clubBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.seasailing.protobuf.ClubDTO, org.seasailing.protobuf.ClubDTO.Builder, org.seasailing.protobuf.ClubDTOOrBuilder>(
                getClub(),
                getParentForChildren(),
                isClean());
        club_ = null;
      }
      return clubBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.seasailing.protobuf.SeriesDTO)
  }

  // @@protoc_insertion_point(class_scope:org.seasailing.protobuf.SeriesDTO)
  private static final org.seasailing.protobuf.SeriesDTO DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.seasailing.protobuf.SeriesDTO();
  }

  public static org.seasailing.protobuf.SeriesDTO getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SeriesDTO>
      PARSER = new com.google.protobuf.AbstractParser<SeriesDTO>() {
    public SeriesDTO parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SeriesDTO(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SeriesDTO> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SeriesDTO> getParserForType() {
    return PARSER;
  }

  public org.seasailing.protobuf.SeriesDTO getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

