package org.seasailing.db.hibernate;
// Generated May 26, 2018, 6:35:30 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Complete generated by hbm2java
 */
@Entity
@Table(name="complete"
    ,catalog="seas"
)
public class Complete  implements java.io.Serializable {


     private Integer completeId;
     private Course course;
     private Series series;
     private Date startTime;
     private Integer seriesmultiplier;
     private String options;
     private Integer denominator;
     private String type;
     private Set<Result> results = new HashSet<Result>(0);

    public Complete() {
    }

	
    public Complete(Course course, Series series, Date startTime, Integer seriesmultiplier, String options) {
        this.course = course;
        this.series = series;
        this.startTime = startTime;
        this.seriesmultiplier = seriesmultiplier;
        this.options = options;
    }
    public Complete(Course course, Series series, Date startTime, Integer seriesmultiplier, String options, Integer denominator, String type, Set<Result> results) {
       this.course = course;
       this.series = series;
       this.startTime = startTime;
       this.seriesmultiplier = seriesmultiplier;
       this.options = options;
       this.denominator = denominator;
       this.type = type;
       this.results = results;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="complete_id", unique=true, nullable=false)
    public Integer getCompleteId() {
        return this.completeId;
    }
    
    public void setCompleteId(Integer completeId) {
        this.completeId = completeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="series_id", nullable=false)
    public Series getSeries() {
        return this.series;
    }
    
    public void setSeries(Series series) {
        this.series = series;
    }

    
    @Column(name="start_time", nullable=false, length=26)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    
    @Column(name="seriesmultiplier", nullable=false)
    public Integer getSeriesmultiplier() {
        return this.seriesmultiplier;
    }
    
    public void setSeriesmultiplier(Integer seriesmultiplier) {
        this.seriesmultiplier = seriesmultiplier;
    }

    
    @Column(name="options", nullable=false, length=3)
    public String getOptions() {
        return this.options;
    }
    
    public void setOptions(String options) {
        this.options = options;
    }

    
    @Column(name="denominator")
    public Integer getDenominator() {
        return this.denominator;
    }
    
    public void setDenominator(Integer denominator) {
        this.denominator = denominator;
    }

    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="complete")
    public Set<Result> getResults() {
        return this.results;
    }
    
    public void setResults(Set<Result> results) {
        this.results = results;
    }




}


