package org.seasailing.db.hibernate;
// Generated May 26, 2018, 6:35:30 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sailboat generated by hbm2java
 */
@Entity
@Table(name="sailboat"
    ,catalog="seas"
)
public class Sailboat  implements java.io.Serializable {


     private Integer sailboatId;
     private Club club;
     private String name;
     private Integer rating;
     private String owner;
     private String make;
     private BigDecimal length;
     private String email;
     private String phone;
     private Boolean active;

    public Sailboat() {
    }

	
    public Sailboat(Club club, String name, Integer rating, String owner, String make, BigDecimal length, Boolean active) {
        this.club = club;
        this.name = name;
        this.rating = rating;
        this.owner = owner;
        this.make = make;
        this.length = length;
        this.active = active;
    }
    public Sailboat(Club club, String name, Integer rating, String owner, String make, BigDecimal length, String email, String phone, Boolean active) {
       this.club = club;
       this.name = name;
       this.rating = rating;
       this.owner = owner;
       this.make = make;
       this.length = length;
       this.email = email;
       this.phone = phone;
       this.active = active;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="sailboat_id", unique=true, nullable=false)
    public Integer getSailboatId() {
        return this.sailboatId;
    }
    
    public void setSailboatId(Integer sailboatId) {
        this.sailboatId = sailboatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="club_id", nullable=false)
    public Club getClub() {
        return this.club;
    }
    
    public void setClub(Club club) {
        this.club = club;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="rating", nullable=false)
    public Integer getRating() {
        return this.rating;
    }
    
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    
    @Column(name="owner", nullable=false, length=100)
    public String getOwner() {
        return this.owner;
    }
    
    public void setOwner(String owner) {
        this.owner = owner;
    }

    
    @Column(name="make", nullable=false, length=50)
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }

    
    @Column(name="length", nullable=false, precision=5)
    public BigDecimal getLength() {
        return this.length;
    }
    
    public void setLength(BigDecimal length) {
        this.length = length;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=8)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="active", nullable=false)
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }




}


