package org.seasailing.db.hibernate;
// Generated May 26, 2018, 6:35:30 PM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Series generated by hbm2java
 */
@Entity
@Table(name="series"
    ,catalog="seas"
)
public class Series  implements java.io.Serializable {


     private Integer seriesId;
     private Club club;
     private String name;
     private String sponsor;
     private Integer seasonmultiplier;
     private String description;
     private Set<Complete> completes = new HashSet<Complete>(0);

    public Series() {
    }

	
    public Series(Club club, String name, String sponsor, Integer seasonmultiplier) {
        this.club = club;
        this.name = name;
        this.sponsor = sponsor;
        this.seasonmultiplier = seasonmultiplier;
    }
    public Series(Club club, String name, String sponsor, Integer seasonmultiplier, String description, Set<Complete> completes) {
       this.club = club;
       this.name = name;
       this.sponsor = sponsor;
       this.seasonmultiplier = seasonmultiplier;
       this.description = description;
       this.completes = completes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="series_id", unique=true, nullable=false)
    public Integer getSeriesId() {
        return this.seriesId;
    }
    
    public void setSeriesId(Integer seriesId) {
        this.seriesId = seriesId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="club_id", nullable=false)
    public Club getClub() {
        return this.club;
    }
    
    public void setClub(Club club) {
        this.club = club;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="sponsor", nullable=false, length=50)
    public String getSponsor() {
        return this.sponsor;
    }
    
    public void setSponsor(String sponsor) {
        this.sponsor = sponsor;
    }

    
    @Column(name="seasonmultiplier", nullable=false)
    public Integer getSeasonmultiplier() {
        return this.seasonmultiplier;
    }
    
    public void setSeasonmultiplier(Integer seasonmultiplier) {
        this.seasonmultiplier = seasonmultiplier;
    }

    
    @Column(name="description", length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="series")
    public Set<Complete> getCompletes() {
        return this.completes;
    }
    
    public void setCompletes(Set<Complete> completes) {
        this.completes = completes;
    }




}


